#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iFrames.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="icraclient")]
	public partial class DSPAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertT_DSP_RETURN_ANALYSIS_SUMMARY(T_DSP_RETURN_ANALYSIS_SUMMARY instance);
    partial void UpdateT_DSP_RETURN_ANALYSIS_SUMMARY(T_DSP_RETURN_ANALYSIS_SUMMARY instance);
    partial void DeleteT_DSP_RETURN_ANALYSIS_SUMMARY(T_DSP_RETURN_ANALYSIS_SUMMARY instance);
    partial void InsertT_DSP_RETURN_ANALYSIS_DETAIL(T_DSP_RETURN_ANALYSIS_DETAIL instance);
    partial void UpdateT_DSP_RETURN_ANALYSIS_DETAIL(T_DSP_RETURN_ANALYSIS_DETAIL instance);
    partial void DeleteT_DSP_RETURN_ANALYSIS_DETAIL(T_DSP_RETURN_ANALYSIS_DETAIL instance);
    partial void InsertT_DSP_LOGIN_MASTER(T_DSP_LOGIN_MASTER instance);
    partial void UpdateT_DSP_LOGIN_MASTER(T_DSP_LOGIN_MASTER instance);
    partial void DeleteT_DSP_LOGIN_MASTER(T_DSP_LOGIN_MASTER instance);
    partial void InsertT_SINGLE_SIGNON(T_SINGLE_SIGNON instance);
    partial void UpdateT_SINGLE_SIGNON(T_SINGLE_SIGNON instance);
    partial void DeleteT_SINGLE_SIGNON(T_SINGLE_SIGNON instance);
    #endregion
		
		public DSPAppDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["csIcraclient"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DSPAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DSPAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DSPAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DSPAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_DSP_RETURN_ANALYSIS_SUMMARY> T_DSP_RETURN_ANALYSIS_SUMMARies
		{
			get
			{
				return this.GetTable<T_DSP_RETURN_ANALYSIS_SUMMARY>();
			}
		}
		
		public System.Data.Linq.Table<T_DSP_RETURN_ANALYSIS_DETAIL> T_DSP_RETURN_ANALYSIS_DETAILs
		{
			get
			{
				return this.GetTable<T_DSP_RETURN_ANALYSIS_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<T_DSP_LOGIN_MASTER> T_DSP_LOGIN_MASTERs
		{
			get
			{
				return this.GetTable<T_DSP_LOGIN_MASTER>();
			}
		}
		
		public System.Data.Linq.Table<T_SINGLE_SIGNON> T_SINGLE_SIGNONs
		{
			get
			{
				return this.GetTable<T_SINGLE_SIGNON>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MFI_IFRAME_DSP_LOGIN_HISTORY")]
		public ISingleResult<MFI_IFRAME_DSP_LOGIN_HISTORYResult> MFI_IFRAME_DSP_LOGIN_HISTORY([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BRANCH_NAME", DbType="VarChar(200)")] string bRANCH_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DATE_FROM", DbType="DateTime")] System.Nullable<System.DateTime> dATE_FROM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DATE_TO", DbType="DateTime")] System.Nullable<System.DateTime> dATE_TO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bRANCH_NAME, dATE_FROM, dATE_TO);
			return ((ISingleResult<MFI_IFRAME_DSP_LOGIN_HISTORYResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_DSP_RETURN_ANALYSIS_SUMMARY")]
	public partial class T_DSP_RETURN_ANALYSIS_SUMMARY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Event_Id;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private string _FILE_NAME;
		
		private string _SHEET_NAME;
		
		private string _CATEGORY;
		
		private string _Fund;
		
		private string _Quartile_Positioning;
		
		private string _Fund_Positioning;
		
		private string _Compound_Annualized_Returns;
		
		private string _Sector_Average;
		
		private string _Median_Top_Quartile;
		
		private string _Sector_Median;
		
		private string _Lowest_in_Top_Quartile;
		
		private string _Rank;
		
		private string _No__of_Funds;
		
		private string _MTD;
		
		private System.Nullable<System.DateTime> _Report_Date;
		
		private string _Loggeduserid;
		
		private System.Nullable<System.DateTime> _Timest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEvent_IdChanging(decimal value);
    partial void OnEvent_IdChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnFILE_NAMEChanging(string value);
    partial void OnFILE_NAMEChanged();
    partial void OnSHEET_NAMEChanging(string value);
    partial void OnSHEET_NAMEChanged();
    partial void OnCATEGORYChanging(string value);
    partial void OnCATEGORYChanged();
    partial void OnFundChanging(string value);
    partial void OnFundChanged();
    partial void OnQuartile_PositioningChanging(string value);
    partial void OnQuartile_PositioningChanged();
    partial void OnFund_PositioningChanging(string value);
    partial void OnFund_PositioningChanged();
    partial void OnCompound_Annualized_ReturnsChanging(string value);
    partial void OnCompound_Annualized_ReturnsChanged();
    partial void OnSector_AverageChanging(string value);
    partial void OnSector_AverageChanged();
    partial void OnMedian_Top_QuartileChanging(string value);
    partial void OnMedian_Top_QuartileChanged();
    partial void OnSector_MedianChanging(string value);
    partial void OnSector_MedianChanged();
    partial void OnLowest_in_Top_QuartileChanging(string value);
    partial void OnLowest_in_Top_QuartileChanged();
    partial void OnRankChanging(string value);
    partial void OnRankChanged();
    partial void OnNo__of_FundsChanging(string value);
    partial void OnNo__of_FundsChanged();
    partial void OnMTDChanging(string value);
    partial void OnMTDChanged();
    partial void OnReport_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnReport_DateChanged();
    partial void OnLoggeduseridChanging(string value);
    partial void OnLoggeduseridChanged();
    partial void OnTimestChanging(System.Nullable<System.DateTime> value);
    partial void OnTimestChanged();
    #endregion
		
		public T_DSP_RETURN_ANALYSIS_SUMMARY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Event_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Event_Id
		{
			get
			{
				return this._Event_Id;
			}
			set
			{
				if ((this._Event_Id != value))
				{
					this.OnEvent_IdChanging(value);
					this.SendPropertyChanging();
					this._Event_Id = value;
					this.SendPropertyChanged("Event_Id");
					this.OnEvent_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_NAME", DbType="VarChar(200)")]
		public string FILE_NAME
		{
			get
			{
				return this._FILE_NAME;
			}
			set
			{
				if ((this._FILE_NAME != value))
				{
					this.OnFILE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FILE_NAME = value;
					this.SendPropertyChanged("FILE_NAME");
					this.OnFILE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHEET_NAME", DbType="VarChar(200)")]
		public string SHEET_NAME
		{
			get
			{
				return this._SHEET_NAME;
			}
			set
			{
				if ((this._SHEET_NAME != value))
				{
					this.OnSHEET_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SHEET_NAME = value;
					this.SendPropertyChanged("SHEET_NAME");
					this.OnSHEET_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY", DbType="VarChar(200)")]
		public string CATEGORY
		{
			get
			{
				return this._CATEGORY;
			}
			set
			{
				if ((this._CATEGORY != value))
				{
					this.OnCATEGORYChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY = value;
					this.SendPropertyChanged("CATEGORY");
					this.OnCATEGORYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fund", DbType="VarChar(200)")]
		public string Fund
		{
			get
			{
				return this._Fund;
			}
			set
			{
				if ((this._Fund != value))
				{
					this.OnFundChanging(value);
					this.SendPropertyChanging();
					this._Fund = value;
					this.SendPropertyChanged("Fund");
					this.OnFundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Quartile Positioning]", Storage="_Quartile_Positioning", DbType="VarChar(200)")]
		public string Quartile_Positioning
		{
			get
			{
				return this._Quartile_Positioning;
			}
			set
			{
				if ((this._Quartile_Positioning != value))
				{
					this.OnQuartile_PositioningChanging(value);
					this.SendPropertyChanging();
					this._Quartile_Positioning = value;
					this.SendPropertyChanged("Quartile_Positioning");
					this.OnQuartile_PositioningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fund Positioning]", Storage="_Fund_Positioning", DbType="VarChar(100)")]
		public string Fund_Positioning
		{
			get
			{
				return this._Fund_Positioning;
			}
			set
			{
				if ((this._Fund_Positioning != value))
				{
					this.OnFund_PositioningChanging(value);
					this.SendPropertyChanging();
					this._Fund_Positioning = value;
					this.SendPropertyChanged("Fund_Positioning");
					this.OnFund_PositioningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Compound Annualized Returns]", Storage="_Compound_Annualized_Returns", DbType="VarChar(50)")]
		public string Compound_Annualized_Returns
		{
			get
			{
				return this._Compound_Annualized_Returns;
			}
			set
			{
				if ((this._Compound_Annualized_Returns != value))
				{
					this.OnCompound_Annualized_ReturnsChanging(value);
					this.SendPropertyChanging();
					this._Compound_Annualized_Returns = value;
					this.SendPropertyChanged("Compound_Annualized_Returns");
					this.OnCompound_Annualized_ReturnsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sector Average]", Storage="_Sector_Average", DbType="VarChar(50)")]
		public string Sector_Average
		{
			get
			{
				return this._Sector_Average;
			}
			set
			{
				if ((this._Sector_Average != value))
				{
					this.OnSector_AverageChanging(value);
					this.SendPropertyChanging();
					this._Sector_Average = value;
					this.SendPropertyChanged("Sector_Average");
					this.OnSector_AverageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Median Top Quartile]", Storage="_Median_Top_Quartile", DbType="VarChar(50)")]
		public string Median_Top_Quartile
		{
			get
			{
				return this._Median_Top_Quartile;
			}
			set
			{
				if ((this._Median_Top_Quartile != value))
				{
					this.OnMedian_Top_QuartileChanging(value);
					this.SendPropertyChanging();
					this._Median_Top_Quartile = value;
					this.SendPropertyChanged("Median_Top_Quartile");
					this.OnMedian_Top_QuartileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sector Median]", Storage="_Sector_Median", DbType="VarChar(50)")]
		public string Sector_Median
		{
			get
			{
				return this._Sector_Median;
			}
			set
			{
				if ((this._Sector_Median != value))
				{
					this.OnSector_MedianChanging(value);
					this.SendPropertyChanging();
					this._Sector_Median = value;
					this.SendPropertyChanged("Sector_Median");
					this.OnSector_MedianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Lowest in Top Quartile]", Storage="_Lowest_in_Top_Quartile", DbType="VarChar(50)")]
		public string Lowest_in_Top_Quartile
		{
			get
			{
				return this._Lowest_in_Top_Quartile;
			}
			set
			{
				if ((this._Lowest_in_Top_Quartile != value))
				{
					this.OnLowest_in_Top_QuartileChanging(value);
					this.SendPropertyChanging();
					this._Lowest_in_Top_Quartile = value;
					this.SendPropertyChanged("Lowest_in_Top_Quartile");
					this.OnLowest_in_Top_QuartileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="VarChar(50)")]
		public string Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this.OnRankChanging(value);
					this.SendPropertyChanging();
					this._Rank = value;
					this.SendPropertyChanged("Rank");
					this.OnRankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[No# of Funds]", Storage="_No__of_Funds", DbType="VarChar(50)")]
		public string No__of_Funds
		{
			get
			{
				return this._No__of_Funds;
			}
			set
			{
				if ((this._No__of_Funds != value))
				{
					this.OnNo__of_FundsChanging(value);
					this.SendPropertyChanging();
					this._No__of_Funds = value;
					this.SendPropertyChanged("No__of_Funds");
					this.OnNo__of_FundsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MTD", DbType="VarChar(50)")]
		public string MTD
		{
			get
			{
				return this._MTD;
			}
			set
			{
				if ((this._MTD != value))
				{
					this.OnMTDChanging(value);
					this.SendPropertyChanging();
					this._MTD = value;
					this.SendPropertyChanged("MTD");
					this.OnMTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Report_Date
		{
			get
			{
				return this._Report_Date;
			}
			set
			{
				if ((this._Report_Date != value))
				{
					this.OnReport_DateChanging(value);
					this.SendPropertyChanging();
					this._Report_Date = value;
					this.SendPropertyChanged("Report_Date");
					this.OnReport_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loggeduserid", DbType="VarChar(200)")]
		public string Loggeduserid
		{
			get
			{
				return this._Loggeduserid;
			}
			set
			{
				if ((this._Loggeduserid != value))
				{
					this.OnLoggeduseridChanging(value);
					this.SendPropertyChanging();
					this._Loggeduserid = value;
					this.SendPropertyChanged("Loggeduserid");
					this.OnLoggeduseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timest", DbType="DateTime")]
		public System.Nullable<System.DateTime> Timest
		{
			get
			{
				return this._Timest;
			}
			set
			{
				if ((this._Timest != value))
				{
					this.OnTimestChanging(value);
					this.SendPropertyChanging();
					this._Timest = value;
					this.SendPropertyChanged("Timest");
					this.OnTimestChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_DSP_RETURN_ANALYSIS_DETAIL")]
	public partial class T_DSP_RETURN_ANALYSIS_DETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Event_Id;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private string _FILE_NAME;
		
		private string _SHEET_NAME;
		
		private string _Column_Name;
		
		private string _Scheme_Name;
		
		private string _AUM;
		
		private string _NAV;
		
		private string @__1_Day;
		
		private string _Rank_1_Day;
		
		private string @__3_Days;
		
		private string _Rank_3_Days;
		
		private string @__7_Days;
		
		private string _Rank_7_Days;
		
		private string @__14_Days;
		
		private string _Rank_14_Days;
		
		private string @__1_Month;
		
		private string _Rank_1_Month;
		
		private string @__3_Months;
		
		private string _Rank_3_Months;
		
		private string @__6_Months;
		
		private string _Rank_6_Months;
		
		private string @__1_Year;
		
		private string _Rank_1_Year;
		
		private string _YTD;
		
		private string _Rank_YTD;
		
		private string @__3_Years;
		
		private string _Rank_3_Years;
		
		private string @__5_Years;
		
		private string _Rank_5_Years;
		
		private string @__8_Years;
		
		private string _Rank_8_Years;
		
		private string @__10_Years;
		
		private string _Rank_10_Years;
		
		private string _Since_Inception;
		
		private string _Rank_Since_Inception;
		
		private string _MTD;
		
		private string _Rank_MTD;
		
		private System.Nullable<System.DateTime> _Report_Date;
		
		private string _Table_Detail;
		
		private string _Loggeduserid;
		
		private System.Nullable<System.DateTime> _Timest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEvent_IdChanging(decimal value);
    partial void OnEvent_IdChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnFILE_NAMEChanging(string value);
    partial void OnFILE_NAMEChanged();
    partial void OnSHEET_NAMEChanging(string value);
    partial void OnSHEET_NAMEChanged();
    partial void OnColumn_NameChanging(string value);
    partial void OnColumn_NameChanged();
    partial void OnScheme_NameChanging(string value);
    partial void OnScheme_NameChanged();
    partial void OnAUMChanging(string value);
    partial void OnAUMChanged();
    partial void OnNAVChanging(string value);
    partial void OnNAVChanged();
    partial void On_1_DayChanging(string value);
    partial void On_1_DayChanged();
    partial void OnRank_1_DayChanging(string value);
    partial void OnRank_1_DayChanged();
    partial void On_3_DaysChanging(string value);
    partial void On_3_DaysChanged();
    partial void OnRank_3_DaysChanging(string value);
    partial void OnRank_3_DaysChanged();
    partial void On_7_DaysChanging(string value);
    partial void On_7_DaysChanged();
    partial void OnRank_7_DaysChanging(string value);
    partial void OnRank_7_DaysChanged();
    partial void On_14_DaysChanging(string value);
    partial void On_14_DaysChanged();
    partial void OnRank_14_DaysChanging(string value);
    partial void OnRank_14_DaysChanged();
    partial void On_1_MonthChanging(string value);
    partial void On_1_MonthChanged();
    partial void OnRank_1_MonthChanging(string value);
    partial void OnRank_1_MonthChanged();
    partial void On_3_MonthsChanging(string value);
    partial void On_3_MonthsChanged();
    partial void OnRank_3_MonthsChanging(string value);
    partial void OnRank_3_MonthsChanged();
    partial void On_6_MonthsChanging(string value);
    partial void On_6_MonthsChanged();
    partial void OnRank_6_MonthsChanging(string value);
    partial void OnRank_6_MonthsChanged();
    partial void On_1_YearChanging(string value);
    partial void On_1_YearChanged();
    partial void OnRank_1_YearChanging(string value);
    partial void OnRank_1_YearChanged();
    partial void OnYTDChanging(string value);
    partial void OnYTDChanged();
    partial void OnRank_YTDChanging(string value);
    partial void OnRank_YTDChanged();
    partial void On_3_YearsChanging(string value);
    partial void On_3_YearsChanged();
    partial void OnRank_3_YearsChanging(string value);
    partial void OnRank_3_YearsChanged();
    partial void On_5_YearsChanging(string value);
    partial void On_5_YearsChanged();
    partial void OnRank_5_YearsChanging(string value);
    partial void OnRank_5_YearsChanged();
    partial void On_8_YearsChanging(string value);
    partial void On_8_YearsChanged();
    partial void OnRank_8_YearsChanging(string value);
    partial void OnRank_8_YearsChanged();
    partial void On_10_YearsChanging(string value);
    partial void On_10_YearsChanged();
    partial void OnRank_10_YearsChanging(string value);
    partial void OnRank_10_YearsChanged();
    partial void OnSince_InceptionChanging(string value);
    partial void OnSince_InceptionChanged();
    partial void OnRank_Since_InceptionChanging(string value);
    partial void OnRank_Since_InceptionChanged();
    partial void OnMTDChanging(string value);
    partial void OnMTDChanged();
    partial void OnRank_MTDChanging(string value);
    partial void OnRank_MTDChanged();
    partial void OnReport_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnReport_DateChanged();
    partial void OnTable_DetailChanging(string value);
    partial void OnTable_DetailChanged();
    partial void OnLoggeduseridChanging(string value);
    partial void OnLoggeduseridChanged();
    partial void OnTimestChanging(System.Nullable<System.DateTime> value);
    partial void OnTimestChanged();
    #endregion
		
		public T_DSP_RETURN_ANALYSIS_DETAIL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Event_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Event_Id
		{
			get
			{
				return this._Event_Id;
			}
			set
			{
				if ((this._Event_Id != value))
				{
					this.OnEvent_IdChanging(value);
					this.SendPropertyChanging();
					this._Event_Id = value;
					this.SendPropertyChanged("Event_Id");
					this.OnEvent_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_NAME", DbType="VarChar(1000)")]
		public string FILE_NAME
		{
			get
			{
				return this._FILE_NAME;
			}
			set
			{
				if ((this._FILE_NAME != value))
				{
					this.OnFILE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FILE_NAME = value;
					this.SendPropertyChanged("FILE_NAME");
					this.OnFILE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHEET_NAME", DbType="VarChar(1000)")]
		public string SHEET_NAME
		{
			get
			{
				return this._SHEET_NAME;
			}
			set
			{
				if ((this._SHEET_NAME != value))
				{
					this.OnSHEET_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SHEET_NAME = value;
					this.SendPropertyChanged("SHEET_NAME");
					this.OnSHEET_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Column_Name", DbType="VarChar(MAX)")]
		public string Column_Name
		{
			get
			{
				return this._Column_Name;
			}
			set
			{
				if ((this._Column_Name != value))
				{
					this.OnColumn_NameChanging(value);
					this.SendPropertyChanging();
					this._Column_Name = value;
					this.SendPropertyChanged("Column_Name");
					this.OnColumn_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Scheme Name]", Storage="_Scheme_Name", DbType="VarChar(200)")]
		public string Scheme_Name
		{
			get
			{
				return this._Scheme_Name;
			}
			set
			{
				if ((this._Scheme_Name != value))
				{
					this.OnScheme_NameChanging(value);
					this.SendPropertyChanging();
					this._Scheme_Name = value;
					this.SendPropertyChanged("Scheme_Name");
					this.OnScheme_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUM", DbType="VarChar(50)")]
		public string AUM
		{
			get
			{
				return this._AUM;
			}
			set
			{
				if ((this._AUM != value))
				{
					this.OnAUMChanging(value);
					this.SendPropertyChanging();
					this._AUM = value;
					this.SendPropertyChanged("AUM");
					this.OnAUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAV", DbType="VarChar(50)")]
		public string NAV
		{
			get
			{
				return this._NAV;
			}
			set
			{
				if ((this._NAV != value))
				{
					this.OnNAVChanging(value);
					this.SendPropertyChanging();
					this._NAV = value;
					this.SendPropertyChanged("NAV");
					this.OnNAVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1 Day]", Storage="__1_Day", DbType="VarChar(50)")]
		public string _1_Day
		{
			get
			{
				return this.@__1_Day;
			}
			set
			{
				if ((this.@__1_Day != value))
				{
					this.On_1_DayChanging(value);
					this.SendPropertyChanging();
					this.@__1_Day = value;
					this.SendPropertyChanged("_1_Day");
					this.On_1_DayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 1 Day]", Storage="_Rank_1_Day", DbType="VarChar(50)")]
		public string Rank_1_Day
		{
			get
			{
				return this._Rank_1_Day;
			}
			set
			{
				if ((this._Rank_1_Day != value))
				{
					this.OnRank_1_DayChanging(value);
					this.SendPropertyChanging();
					this._Rank_1_Day = value;
					this.SendPropertyChanged("Rank_1_Day");
					this.OnRank_1_DayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3 Days]", Storage="__3_Days", DbType="VarChar(50)")]
		public string _3_Days
		{
			get
			{
				return this.@__3_Days;
			}
			set
			{
				if ((this.@__3_Days != value))
				{
					this.On_3_DaysChanging(value);
					this.SendPropertyChanging();
					this.@__3_Days = value;
					this.SendPropertyChanged("_3_Days");
					this.On_3_DaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 3 Days]", Storage="_Rank_3_Days", DbType="VarChar(50)")]
		public string Rank_3_Days
		{
			get
			{
				return this._Rank_3_Days;
			}
			set
			{
				if ((this._Rank_3_Days != value))
				{
					this.OnRank_3_DaysChanging(value);
					this.SendPropertyChanging();
					this._Rank_3_Days = value;
					this.SendPropertyChanged("Rank_3_Days");
					this.OnRank_3_DaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[7 Days]", Storage="__7_Days", DbType="VarChar(50)")]
		public string _7_Days
		{
			get
			{
				return this.@__7_Days;
			}
			set
			{
				if ((this.@__7_Days != value))
				{
					this.On_7_DaysChanging(value);
					this.SendPropertyChanging();
					this.@__7_Days = value;
					this.SendPropertyChanged("_7_Days");
					this.On_7_DaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 7 Days]", Storage="_Rank_7_Days", DbType="VarChar(50)")]
		public string Rank_7_Days
		{
			get
			{
				return this._Rank_7_Days;
			}
			set
			{
				if ((this._Rank_7_Days != value))
				{
					this.OnRank_7_DaysChanging(value);
					this.SendPropertyChanging();
					this._Rank_7_Days = value;
					this.SendPropertyChanged("Rank_7_Days");
					this.OnRank_7_DaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[14 Days]", Storage="__14_Days", DbType="VarChar(50)")]
		public string _14_Days
		{
			get
			{
				return this.@__14_Days;
			}
			set
			{
				if ((this.@__14_Days != value))
				{
					this.On_14_DaysChanging(value);
					this.SendPropertyChanging();
					this.@__14_Days = value;
					this.SendPropertyChanged("_14_Days");
					this.On_14_DaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 14 Days]", Storage="_Rank_14_Days", DbType="VarChar(50)")]
		public string Rank_14_Days
		{
			get
			{
				return this._Rank_14_Days;
			}
			set
			{
				if ((this._Rank_14_Days != value))
				{
					this.OnRank_14_DaysChanging(value);
					this.SendPropertyChanging();
					this._Rank_14_Days = value;
					this.SendPropertyChanged("Rank_14_Days");
					this.OnRank_14_DaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1 Month]", Storage="__1_Month", DbType="VarChar(50)")]
		public string _1_Month
		{
			get
			{
				return this.@__1_Month;
			}
			set
			{
				if ((this.@__1_Month != value))
				{
					this.On_1_MonthChanging(value);
					this.SendPropertyChanging();
					this.@__1_Month = value;
					this.SendPropertyChanged("_1_Month");
					this.On_1_MonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 1 Month]", Storage="_Rank_1_Month", DbType="VarChar(50)")]
		public string Rank_1_Month
		{
			get
			{
				return this._Rank_1_Month;
			}
			set
			{
				if ((this._Rank_1_Month != value))
				{
					this.OnRank_1_MonthChanging(value);
					this.SendPropertyChanging();
					this._Rank_1_Month = value;
					this.SendPropertyChanged("Rank_1_Month");
					this.OnRank_1_MonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3 Months]", Storage="__3_Months", DbType="VarChar(50)")]
		public string _3_Months
		{
			get
			{
				return this.@__3_Months;
			}
			set
			{
				if ((this.@__3_Months != value))
				{
					this.On_3_MonthsChanging(value);
					this.SendPropertyChanging();
					this.@__3_Months = value;
					this.SendPropertyChanged("_3_Months");
					this.On_3_MonthsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 3 Months]", Storage="_Rank_3_Months", DbType="VarChar(50)")]
		public string Rank_3_Months
		{
			get
			{
				return this._Rank_3_Months;
			}
			set
			{
				if ((this._Rank_3_Months != value))
				{
					this.OnRank_3_MonthsChanging(value);
					this.SendPropertyChanging();
					this._Rank_3_Months = value;
					this.SendPropertyChanged("Rank_3_Months");
					this.OnRank_3_MonthsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[6 Months]", Storage="__6_Months", DbType="VarChar(50)")]
		public string _6_Months
		{
			get
			{
				return this.@__6_Months;
			}
			set
			{
				if ((this.@__6_Months != value))
				{
					this.On_6_MonthsChanging(value);
					this.SendPropertyChanging();
					this.@__6_Months = value;
					this.SendPropertyChanged("_6_Months");
					this.On_6_MonthsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 6 Months]", Storage="_Rank_6_Months", DbType="VarChar(50)")]
		public string Rank_6_Months
		{
			get
			{
				return this._Rank_6_Months;
			}
			set
			{
				if ((this._Rank_6_Months != value))
				{
					this.OnRank_6_MonthsChanging(value);
					this.SendPropertyChanging();
					this._Rank_6_Months = value;
					this.SendPropertyChanged("Rank_6_Months");
					this.OnRank_6_MonthsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1 Year]", Storage="__1_Year", DbType="VarChar(50)")]
		public string _1_Year
		{
			get
			{
				return this.@__1_Year;
			}
			set
			{
				if ((this.@__1_Year != value))
				{
					this.On_1_YearChanging(value);
					this.SendPropertyChanging();
					this.@__1_Year = value;
					this.SendPropertyChanged("_1_Year");
					this.On_1_YearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 1 Year]", Storage="_Rank_1_Year", DbType="VarChar(50)")]
		public string Rank_1_Year
		{
			get
			{
				return this._Rank_1_Year;
			}
			set
			{
				if ((this._Rank_1_Year != value))
				{
					this.OnRank_1_YearChanging(value);
					this.SendPropertyChanging();
					this._Rank_1_Year = value;
					this.SendPropertyChanged("Rank_1_Year");
					this.OnRank_1_YearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YTD", DbType="VarChar(50)")]
		public string YTD
		{
			get
			{
				return this._YTD;
			}
			set
			{
				if ((this._YTD != value))
				{
					this.OnYTDChanging(value);
					this.SendPropertyChanging();
					this._YTD = value;
					this.SendPropertyChanged("YTD");
					this.OnYTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank YTD]", Storage="_Rank_YTD", DbType="VarChar(50)")]
		public string Rank_YTD
		{
			get
			{
				return this._Rank_YTD;
			}
			set
			{
				if ((this._Rank_YTD != value))
				{
					this.OnRank_YTDChanging(value);
					this.SendPropertyChanging();
					this._Rank_YTD = value;
					this.SendPropertyChanged("Rank_YTD");
					this.OnRank_YTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3 Years]", Storage="__3_Years", DbType="VarChar(50)")]
		public string _3_Years
		{
			get
			{
				return this.@__3_Years;
			}
			set
			{
				if ((this.@__3_Years != value))
				{
					this.On_3_YearsChanging(value);
					this.SendPropertyChanging();
					this.@__3_Years = value;
					this.SendPropertyChanged("_3_Years");
					this.On_3_YearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 3 Years]", Storage="_Rank_3_Years", DbType="VarChar(50)")]
		public string Rank_3_Years
		{
			get
			{
				return this._Rank_3_Years;
			}
			set
			{
				if ((this._Rank_3_Years != value))
				{
					this.OnRank_3_YearsChanging(value);
					this.SendPropertyChanging();
					this._Rank_3_Years = value;
					this.SendPropertyChanged("Rank_3_Years");
					this.OnRank_3_YearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[5 Years]", Storage="__5_Years", DbType="VarChar(50)")]
		public string _5_Years
		{
			get
			{
				return this.@__5_Years;
			}
			set
			{
				if ((this.@__5_Years != value))
				{
					this.On_5_YearsChanging(value);
					this.SendPropertyChanging();
					this.@__5_Years = value;
					this.SendPropertyChanged("_5_Years");
					this.On_5_YearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 5 Years]", Storage="_Rank_5_Years", DbType="VarChar(50)")]
		public string Rank_5_Years
		{
			get
			{
				return this._Rank_5_Years;
			}
			set
			{
				if ((this._Rank_5_Years != value))
				{
					this.OnRank_5_YearsChanging(value);
					this.SendPropertyChanging();
					this._Rank_5_Years = value;
					this.SendPropertyChanged("Rank_5_Years");
					this.OnRank_5_YearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[8 Years]", Storage="__8_Years", DbType="VarChar(50)")]
		public string _8_Years
		{
			get
			{
				return this.@__8_Years;
			}
			set
			{
				if ((this.@__8_Years != value))
				{
					this.On_8_YearsChanging(value);
					this.SendPropertyChanging();
					this.@__8_Years = value;
					this.SendPropertyChanged("_8_Years");
					this.On_8_YearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 8 Years]", Storage="_Rank_8_Years", DbType="VarChar(50)")]
		public string Rank_8_Years
		{
			get
			{
				return this._Rank_8_Years;
			}
			set
			{
				if ((this._Rank_8_Years != value))
				{
					this.OnRank_8_YearsChanging(value);
					this.SendPropertyChanging();
					this._Rank_8_Years = value;
					this.SendPropertyChanged("Rank_8_Years");
					this.OnRank_8_YearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[10 Years]", Storage="__10_Years", DbType="VarChar(50)")]
		public string _10_Years
		{
			get
			{
				return this.@__10_Years;
			}
			set
			{
				if ((this.@__10_Years != value))
				{
					this.On_10_YearsChanging(value);
					this.SendPropertyChanging();
					this.@__10_Years = value;
					this.SendPropertyChanged("_10_Years");
					this.On_10_YearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank 10 Years]", Storage="_Rank_10_Years", DbType="VarChar(50)")]
		public string Rank_10_Years
		{
			get
			{
				return this._Rank_10_Years;
			}
			set
			{
				if ((this._Rank_10_Years != value))
				{
					this.OnRank_10_YearsChanging(value);
					this.SendPropertyChanging();
					this._Rank_10_Years = value;
					this.SendPropertyChanged("Rank_10_Years");
					this.OnRank_10_YearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Since Inception]", Storage="_Since_Inception", DbType="VarChar(50)")]
		public string Since_Inception
		{
			get
			{
				return this._Since_Inception;
			}
			set
			{
				if ((this._Since_Inception != value))
				{
					this.OnSince_InceptionChanging(value);
					this.SendPropertyChanging();
					this._Since_Inception = value;
					this.SendPropertyChanged("Since_Inception");
					this.OnSince_InceptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank Since Inception]", Storage="_Rank_Since_Inception", DbType="VarChar(50)")]
		public string Rank_Since_Inception
		{
			get
			{
				return this._Rank_Since_Inception;
			}
			set
			{
				if ((this._Rank_Since_Inception != value))
				{
					this.OnRank_Since_InceptionChanging(value);
					this.SendPropertyChanging();
					this._Rank_Since_Inception = value;
					this.SendPropertyChanged("Rank_Since_Inception");
					this.OnRank_Since_InceptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MTD", DbType="VarChar(50)")]
		public string MTD
		{
			get
			{
				return this._MTD;
			}
			set
			{
				if ((this._MTD != value))
				{
					this.OnMTDChanging(value);
					this.SendPropertyChanging();
					this._MTD = value;
					this.SendPropertyChanged("MTD");
					this.OnMTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rank MTD]", Storage="_Rank_MTD", DbType="VarChar(50)")]
		public string Rank_MTD
		{
			get
			{
				return this._Rank_MTD;
			}
			set
			{
				if ((this._Rank_MTD != value))
				{
					this.OnRank_MTDChanging(value);
					this.SendPropertyChanging();
					this._Rank_MTD = value;
					this.SendPropertyChanged("Rank_MTD");
					this.OnRank_MTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Report_Date
		{
			get
			{
				return this._Report_Date;
			}
			set
			{
				if ((this._Report_Date != value))
				{
					this.OnReport_DateChanging(value);
					this.SendPropertyChanging();
					this._Report_Date = value;
					this.SendPropertyChanged("Report_Date");
					this.OnReport_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Table Detail]", Storage="_Table_Detail", DbType="VarChar(50)")]
		public string Table_Detail
		{
			get
			{
				return this._Table_Detail;
			}
			set
			{
				if ((this._Table_Detail != value))
				{
					this.OnTable_DetailChanging(value);
					this.SendPropertyChanging();
					this._Table_Detail = value;
					this.SendPropertyChanged("Table_Detail");
					this.OnTable_DetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loggeduserid", DbType="VarChar(200)")]
		public string Loggeduserid
		{
			get
			{
				return this._Loggeduserid;
			}
			set
			{
				if ((this._Loggeduserid != value))
				{
					this.OnLoggeduseridChanging(value);
					this.SendPropertyChanging();
					this._Loggeduserid = value;
					this.SendPropertyChanged("Loggeduserid");
					this.OnLoggeduseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timest", DbType="DateTime")]
		public System.Nullable<System.DateTime> Timest
		{
			get
			{
				return this._Timest;
			}
			set
			{
				if ((this._Timest != value))
				{
					this.OnTimestChanging(value);
					this.SendPropertyChanging();
					this._Timest = value;
					this.SendPropertyChanged("Timest");
					this.OnTimestChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_DSP_LOGIN_MASTER")]
	public partial class T_DSP_LOGIN_MASTER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Id;
		
		private string _Email_Id;
		
		private string _Password;
		
		private System.Nullable<System.DateTime> _Last_Login_Date;
		
		private System.DateTime _Password_Changed_Date;
		
		private int _Wrong_Attmept_Count;
		
		private string _Comment;
		
		private int _Created_By;
		
		private System.DateTime _Created_On;
		
		private System.Nullable<int> _Modified_BY;
		
		private System.Nullable<System.DateTime> _Modified_On;
		
		private bool _IsActive;
		
		private System.Nullable<System.DateTime> _Last_Locked_Out_Date;
		
		private System.Nullable<bool> _IsLockedOut;
		
		private System.Nullable<bool> _IsOnLine;
		
		private System.Nullable<bool> _IsAdmin;
		
		private string _BRANCH_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdChanging(int value);
    partial void OnUser_IdChanged();
    partial void OnEmail_IdChanging(string value);
    partial void OnEmail_IdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnLast_Login_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnLast_Login_DateChanged();
    partial void OnPassword_Changed_DateChanging(System.DateTime value);
    partial void OnPassword_Changed_DateChanged();
    partial void OnWrong_Attmept_CountChanging(int value);
    partial void OnWrong_Attmept_CountChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnCreated_ByChanging(int value);
    partial void OnCreated_ByChanged();
    partial void OnCreated_OnChanging(System.DateTime value);
    partial void OnCreated_OnChanged();
    partial void OnModified_BYChanging(System.Nullable<int> value);
    partial void OnModified_BYChanged();
    partial void OnModified_OnChanging(System.Nullable<System.DateTime> value);
    partial void OnModified_OnChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnLast_Locked_Out_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnLast_Locked_Out_DateChanged();
    partial void OnIsLockedOutChanging(System.Nullable<bool> value);
    partial void OnIsLockedOutChanged();
    partial void OnIsOnLineChanging(System.Nullable<bool> value);
    partial void OnIsOnLineChanged();
    partial void OnIsAdminChanging(System.Nullable<bool> value);
    partial void OnIsAdminChanged();
    partial void OnBRANCH_NAMEChanging(string value);
    partial void OnBRANCH_NAMEChanged();
    #endregion
		
		public T_DSP_LOGIN_MASTER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_Id", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Email_Id
		{
			get
			{
				return this._Email_Id;
			}
			set
			{
				if ((this._Email_Id != value))
				{
					this.OnEmail_IdChanging(value);
					this.SendPropertyChanging();
					this._Email_Id = value;
					this.SendPropertyChanged("Email_Id");
					this.OnEmail_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Login_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Last_Login_Date
		{
			get
			{
				return this._Last_Login_Date;
			}
			set
			{
				if ((this._Last_Login_Date != value))
				{
					this.OnLast_Login_DateChanging(value);
					this.SendPropertyChanging();
					this._Last_Login_Date = value;
					this.SendPropertyChanged("Last_Login_Date");
					this.OnLast_Login_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_Changed_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Password_Changed_Date
		{
			get
			{
				return this._Password_Changed_Date;
			}
			set
			{
				if ((this._Password_Changed_Date != value))
				{
					this.OnPassword_Changed_DateChanging(value);
					this.SendPropertyChanging();
					this._Password_Changed_Date = value;
					this.SendPropertyChanged("Password_Changed_Date");
					this.OnPassword_Changed_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wrong_Attmept_Count", DbType="Int NOT NULL")]
		public int Wrong_Attmept_Count
		{
			get
			{
				return this._Wrong_Attmept_Count;
			}
			set
			{
				if ((this._Wrong_Attmept_Count != value))
				{
					this.OnWrong_Attmept_CountChanging(value);
					this.SendPropertyChanging();
					this._Wrong_Attmept_Count = value;
					this.SendPropertyChanged("Wrong_Attmept_Count");
					this.OnWrong_Attmept_CountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(200)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_By", DbType="Int NOT NULL")]
		public int Created_By
		{
			get
			{
				return this._Created_By;
			}
			set
			{
				if ((this._Created_By != value))
				{
					this.OnCreated_ByChanging(value);
					this.SendPropertyChanging();
					this._Created_By = value;
					this.SendPropertyChanged("Created_By");
					this.OnCreated_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_On", DbType="DateTime NOT NULL")]
		public System.DateTime Created_On
		{
			get
			{
				return this._Created_On;
			}
			set
			{
				if ((this._Created_On != value))
				{
					this.OnCreated_OnChanging(value);
					this.SendPropertyChanging();
					this._Created_On = value;
					this.SendPropertyChanged("Created_On");
					this.OnCreated_OnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_BY", DbType="Int")]
		public System.Nullable<int> Modified_BY
		{
			get
			{
				return this._Modified_BY;
			}
			set
			{
				if ((this._Modified_BY != value))
				{
					this.OnModified_BYChanging(value);
					this.SendPropertyChanging();
					this._Modified_BY = value;
					this.SendPropertyChanged("Modified_BY");
					this.OnModified_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_On", DbType="DateTime")]
		public System.Nullable<System.DateTime> Modified_On
		{
			get
			{
				return this._Modified_On;
			}
			set
			{
				if ((this._Modified_On != value))
				{
					this.OnModified_OnChanging(value);
					this.SendPropertyChanging();
					this._Modified_On = value;
					this.SendPropertyChanged("Modified_On");
					this.OnModified_OnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Locked_Out_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Last_Locked_Out_Date
		{
			get
			{
				return this._Last_Locked_Out_Date;
			}
			set
			{
				if ((this._Last_Locked_Out_Date != value))
				{
					this.OnLast_Locked_Out_DateChanging(value);
					this.SendPropertyChanging();
					this._Last_Locked_Out_Date = value;
					this.SendPropertyChanged("Last_Locked_Out_Date");
					this.OnLast_Locked_Out_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLockedOut", DbType="Bit")]
		public System.Nullable<bool> IsLockedOut
		{
			get
			{
				return this._IsLockedOut;
			}
			set
			{
				if ((this._IsLockedOut != value))
				{
					this.OnIsLockedOutChanging(value);
					this.SendPropertyChanging();
					this._IsLockedOut = value;
					this.SendPropertyChanged("IsLockedOut");
					this.OnIsLockedOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOnLine", DbType="Bit")]
		public System.Nullable<bool> IsOnLine
		{
			get
			{
				return this._IsOnLine;
			}
			set
			{
				if ((this._IsOnLine != value))
				{
					this.OnIsOnLineChanging(value);
					this.SendPropertyChanging();
					this._IsOnLine = value;
					this.SendPropertyChanged("IsOnLine");
					this.OnIsOnLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit")]
		public System.Nullable<bool> IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this.OnIsAdminChanging(value);
					this.SendPropertyChanging();
					this._IsAdmin = value;
					this.SendPropertyChanged("IsAdmin");
					this.OnIsAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_NAME", DbType="VarChar(200)")]
		public string BRANCH_NAME
		{
			get
			{
				return this._BRANCH_NAME;
			}
			set
			{
				if ((this._BRANCH_NAME != value))
				{
					this.OnBRANCH_NAMEChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_NAME = value;
					this.SendPropertyChanged("BRANCH_NAME");
					this.OnBRANCH_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_SINGLE_SIGNON")]
	public partial class T_SINGLE_SIGNON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _External_Login_Id;
		
		private int _Client_Id;
		
		private string _User_Id;
		
		private string _Password;
		
		private int _Created_By;
		
		private System.DateTime _Created_On;
		
		private System.Nullable<int> _Modified_BY;
		
		private System.Nullable<System.DateTime> _Modified_On;
		
		private bool _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExternal_Login_IdChanging(int value);
    partial void OnExternal_Login_IdChanged();
    partial void OnClient_IdChanging(int value);
    partial void OnClient_IdChanged();
    partial void OnUser_IdChanging(string value);
    partial void OnUser_IdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnCreated_ByChanging(int value);
    partial void OnCreated_ByChanged();
    partial void OnCreated_OnChanging(System.DateTime value);
    partial void OnCreated_OnChanged();
    partial void OnModified_BYChanging(System.Nullable<int> value);
    partial void OnModified_BYChanged();
    partial void OnModified_OnChanging(System.Nullable<System.DateTime> value);
    partial void OnModified_OnChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    #endregion
		
		public T_SINGLE_SIGNON()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_External_Login_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int External_Login_Id
		{
			get
			{
				return this._External_Login_Id;
			}
			set
			{
				if ((this._External_Login_Id != value))
				{
					this.OnExternal_Login_IdChanging(value);
					this.SendPropertyChanging();
					this._External_Login_Id = value;
					this.SendPropertyChanged("External_Login_Id");
					this.OnExternal_Login_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client_Id", DbType="Int NOT NULL")]
		public int Client_Id
		{
			get
			{
				return this._Client_Id;
			}
			set
			{
				if ((this._Client_Id != value))
				{
					this.OnClient_IdChanging(value);
					this.SendPropertyChanging();
					this._Client_Id = value;
					this.SendPropertyChanged("Client_Id");
					this.OnClient_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="VarChar(250)")]
		public string User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_By", DbType="Int NOT NULL")]
		public int Created_By
		{
			get
			{
				return this._Created_By;
			}
			set
			{
				if ((this._Created_By != value))
				{
					this.OnCreated_ByChanging(value);
					this.SendPropertyChanging();
					this._Created_By = value;
					this.SendPropertyChanged("Created_By");
					this.OnCreated_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_On", DbType="DateTime NOT NULL")]
		public System.DateTime Created_On
		{
			get
			{
				return this._Created_On;
			}
			set
			{
				if ((this._Created_On != value))
				{
					this.OnCreated_OnChanging(value);
					this.SendPropertyChanging();
					this._Created_On = value;
					this.SendPropertyChanged("Created_On");
					this.OnCreated_OnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_BY", DbType="Int")]
		public System.Nullable<int> Modified_BY
		{
			get
			{
				return this._Modified_BY;
			}
			set
			{
				if ((this._Modified_BY != value))
				{
					this.OnModified_BYChanging(value);
					this.SendPropertyChanging();
					this._Modified_BY = value;
					this.SendPropertyChanged("Modified_BY");
					this.OnModified_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_On", DbType="DateTime")]
		public System.Nullable<System.DateTime> Modified_On
		{
			get
			{
				return this._Modified_On;
			}
			set
			{
				if ((this._Modified_On != value))
				{
					this.OnModified_OnChanging(value);
					this.SendPropertyChanging();
					this._Modified_On = value;
					this.SendPropertyChanged("Modified_On");
					this.OnModified_OnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class MFI_IFRAME_DSP_LOGIN_HISTORYResult
	{
		
		private string _EMAIL_ID;
		
		private System.Nullable<System.DateTime> _LAST_LOGIN;
		
		private System.Nullable<int> _LOGIN_COUNT;
		
		private string _BRANCH_NAME;
		
		public MFI_IFRAME_DSP_LOGIN_HISTORYResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_ID", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string EMAIL_ID
		{
			get
			{
				return this._EMAIL_ID;
			}
			set
			{
				if ((this._EMAIL_ID != value))
				{
					this._EMAIL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_LOGIN", DbType="DateTime")]
		public System.Nullable<System.DateTime> LAST_LOGIN
		{
			get
			{
				return this._LAST_LOGIN;
			}
			set
			{
				if ((this._LAST_LOGIN != value))
				{
					this._LAST_LOGIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGIN_COUNT", DbType="Int")]
		public System.Nullable<int> LOGIN_COUNT
		{
			get
			{
				return this._LOGIN_COUNT;
			}
			set
			{
				if ((this._LOGIN_COUNT != value))
				{
					this._LOGIN_COUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_NAME", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string BRANCH_NAME
		{
			get
			{
				return this._BRANCH_NAME;
			}
			set
			{
				if ((this._BRANCH_NAME != value))
				{
					this._BRANCH_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
