#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iFrames.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="indiacapital")]
	public partial class iFramesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public iFramesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["csIndiaCapital"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public iFramesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iFramesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iFramesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iFramesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<mut_fund> mut_funds
		{
			get
			{
				return this.GetTable<mut_fund>();
			}
		}
		
		public System.Data.Linq.Table<AMC> AMCs
		{
			get
			{
				return this.GetTable<AMC>();
			}
		}
		
		public System.Data.Linq.Table<top_fund> top_funds
		{
			get
			{
				return this.GetTable<top_fund>();
			}
		}
		
		public System.Data.Linq.Table<REGIST> REGISTs
		{
			get
			{
				return this.GetTable<REGIST>();
			}
		}
		
		public System.Data.Linq.Table<latest_nav> latest_navs
		{
			get
			{
				return this.GetTable<latest_nav>();
			}
		}
		
		public System.Data.Linq.Table<div_rec> div_recs
		{
			get
			{
				return this.GetTable<div_rec>();
			}
		}
		
		public System.Data.Linq.Table<net_ind_pot1> net_ind_pot1s
		{
			get
			{
				return this.GetTable<net_ind_pot1>();
			}
		}
		
		public System.Data.Linq.Table<Invt_Pat> Invt_Pats
		{
			get
			{
				return this.GetTable<Invt_Pat>();
			}
		}
		
		public System.Data.Linq.Table<top_hold> top_holds
		{
			get
			{
				return this.GetTable<top_hold>();
			}
		}
		
		public System.Data.Linq.Table<FundSize> FundSizes
		{
			get
			{
				return this.GetTable<FundSize>();
			}
		}
		
		public System.Data.Linq.Table<Fund_Manager> Fund_Managers
		{
			get
			{
				return this.GetTable<Fund_Manager>();
			}
		}
		
		public System.Data.Linq.Table<cur_fund_man> cur_fund_mans
		{
			get
			{
				return this.GetTable<cur_fund_man>();
			}
		}
		
		public System.Data.Linq.Table<nav_new> nav_news
		{
			get
			{
				return this.GetTable<nav_new>();
			}
		}
		
		public System.Data.Linq.Table<mfi_new> mfi_news
		{
			get
			{
				return this.GetTable<mfi_new>();
			}
		}
		
		public System.Data.Linq.Table<Com_detail> Com_details
		{
			get
			{
				return this.GetTable<Com_detail>();
			}
		}
		
		public System.Data.Linq.Table<Sector_ind> Sector_inds
		{
			get
			{
				return this.GetTable<Sector_ind>();
			}
		}
		
		public System.Data.Linq.Table<front_new> front_news
		{
			get
			{
				return this.GetTable<front_new>();
			}
		}
		
		public System.Data.Linq.Table<net_com_pot> net_com_pots
		{
			get
			{
				return this.GetTable<net_com_pot>();
			}
		}
		
		public System.Data.Linq.Table<Sector> Sectors
		{
			get
			{
				return this.GetTable<Sector>();
			}
		}
		
		public System.Data.Linq.Table<sch_nature_detail> sch_nature_details
		{
			get
			{
				return this.GetTable<sch_nature_detail>();
			}
		}
		
		public System.Data.Linq.Table<ind_info> ind_infos
		{
			get
			{
				return this.GetTable<ind_info>();
			}
		}
		
		public System.Data.Linq.Table<amc_detail> amc_details
		{
			get
			{
				return this.GetTable<amc_detail>();
			}
		}
		
		public System.Data.Linq.Table<AverageCorpus> AverageCorpus
		{
			get
			{
				return this.GetTable<AverageCorpus>();
			}
		}
		
		public System.Data.Linq.Table<AUM> AUMs
		{
			get
			{
				return this.GetTable<AUM>();
			}
		}
		
		public System.Data.Linq.Table<amfi> amfis
		{
			get
			{
				return this.GetTable<amfi>();
			}
		}
		
		public System.Data.Linq.Table<corpus> corpus
		{
			get
			{
				return this.GetTable<corpus>();
			}
		}
		
		public System.Data.Linq.Table<Book_Close> Book_Closes
		{
			get
			{
				return this.GetTable<Book_Close>();
			}
		}
		
		public System.Data.Linq.Table<mut_br> mut_brs
		{
			get
			{
				return this.GetTable<mut_br>();
			}
		}
		
		public System.Data.Linq.Table<sale_purchase> sale_purchases
		{
			get
			{
				return this.GetTable<sale_purchase>();
			}
		}
		
		public System.Data.Linq.Table<exitentry_load> exitentry_loads
		{
			get
			{
				return this.GetTable<exitentry_load>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MUT_FUND")]
	public partial class mut_fund
	{
		
		private string _Mut_Code;
		
		private string _Mut_Name;
		
		private string _E_Mail;
		
		private string _Web_Site;
		
		private string _Reg_Add1;
		
		private string _Reg_Add2;
		
		private string _Reg_city;
		
		private string _Reg_Pin;
		
		private string _Reg_Phone1;
		
		private string _Reg_Phone2;
		
		private string _Reg_Phone3;
		
		private string _Reg_Fax;
		
		private string _Reg_Conper;
		
		private string _Cor_Add1;
		
		private string _Cor_Add2;
		
		private string _Cor_City;
		
		private string _Cor_Pin;
		
		private string _Cor_Phone1;
		
		private string _Cor_Phone2;
		
		private string _Cor_Phone3;
		
		private string _Cor_Fax;
		
		private string _Cor_Conper;
		
		private string _partner;
		
		public mut_fund()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mut_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Mut_Code
		{
			get
			{
				return this._Mut_Code;
			}
			set
			{
				if ((this._Mut_Code != value))
				{
					this._Mut_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mut_Name", DbType="VarChar(80)")]
		public string Mut_Name
		{
			get
			{
				return this._Mut_Name;
			}
			set
			{
				if ((this._Mut_Name != value))
				{
					this._Mut_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Mail", DbType="VarChar(45)")]
		public string E_Mail
		{
			get
			{
				return this._E_Mail;
			}
			set
			{
				if ((this._E_Mail != value))
				{
					this._E_Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web_Site", DbType="VarChar(45)")]
		public string Web_Site
		{
			get
			{
				return this._Web_Site;
			}
			set
			{
				if ((this._Web_Site != value))
				{
					this._Web_Site = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_Add1", DbType="VarChar(50)")]
		public string Reg_Add1
		{
			get
			{
				return this._Reg_Add1;
			}
			set
			{
				if ((this._Reg_Add1 != value))
				{
					this._Reg_Add1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_Add2", DbType="VarChar(50)")]
		public string Reg_Add2
		{
			get
			{
				return this._Reg_Add2;
			}
			set
			{
				if ((this._Reg_Add2 != value))
				{
					this._Reg_Add2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_city", DbType="VarChar(20)")]
		public string Reg_city
		{
			get
			{
				return this._Reg_city;
			}
			set
			{
				if ((this._Reg_city != value))
				{
					this._Reg_city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_Pin", DbType="VarChar(6)")]
		public string Reg_Pin
		{
			get
			{
				return this._Reg_Pin;
			}
			set
			{
				if ((this._Reg_Pin != value))
				{
					this._Reg_Pin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_Phone1", DbType="VarChar(10)")]
		public string Reg_Phone1
		{
			get
			{
				return this._Reg_Phone1;
			}
			set
			{
				if ((this._Reg_Phone1 != value))
				{
					this._Reg_Phone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_Phone2", DbType="VarChar(10)")]
		public string Reg_Phone2
		{
			get
			{
				return this._Reg_Phone2;
			}
			set
			{
				if ((this._Reg_Phone2 != value))
				{
					this._Reg_Phone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_Phone3", DbType="VarChar(10)")]
		public string Reg_Phone3
		{
			get
			{
				return this._Reg_Phone3;
			}
			set
			{
				if ((this._Reg_Phone3 != value))
				{
					this._Reg_Phone3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_Fax", DbType="VarChar(10)")]
		public string Reg_Fax
		{
			get
			{
				return this._Reg_Fax;
			}
			set
			{
				if ((this._Reg_Fax != value))
				{
					this._Reg_Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_Conper", DbType="VarChar(45)")]
		public string Reg_Conper
		{
			get
			{
				return this._Reg_Conper;
			}
			set
			{
				if ((this._Reg_Conper != value))
				{
					this._Reg_Conper = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor_Add1", DbType="VarChar(50)")]
		public string Cor_Add1
		{
			get
			{
				return this._Cor_Add1;
			}
			set
			{
				if ((this._Cor_Add1 != value))
				{
					this._Cor_Add1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor_Add2", DbType="VarChar(50)")]
		public string Cor_Add2
		{
			get
			{
				return this._Cor_Add2;
			}
			set
			{
				if ((this._Cor_Add2 != value))
				{
					this._Cor_Add2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor_City", DbType="VarChar(20)")]
		public string Cor_City
		{
			get
			{
				return this._Cor_City;
			}
			set
			{
				if ((this._Cor_City != value))
				{
					this._Cor_City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor_Pin", DbType="VarChar(6)")]
		public string Cor_Pin
		{
			get
			{
				return this._Cor_Pin;
			}
			set
			{
				if ((this._Cor_Pin != value))
				{
					this._Cor_Pin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor_Phone1", DbType="VarChar(10)")]
		public string Cor_Phone1
		{
			get
			{
				return this._Cor_Phone1;
			}
			set
			{
				if ((this._Cor_Phone1 != value))
				{
					this._Cor_Phone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor_Phone2", DbType="VarChar(10)")]
		public string Cor_Phone2
		{
			get
			{
				return this._Cor_Phone2;
			}
			set
			{
				if ((this._Cor_Phone2 != value))
				{
					this._Cor_Phone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor_Phone3", DbType="VarChar(10)")]
		public string Cor_Phone3
		{
			get
			{
				return this._Cor_Phone3;
			}
			set
			{
				if ((this._Cor_Phone3 != value))
				{
					this._Cor_Phone3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor_Fax", DbType="VarChar(10)")]
		public string Cor_Fax
		{
			get
			{
				return this._Cor_Fax;
			}
			set
			{
				if ((this._Cor_Fax != value))
				{
					this._Cor_Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor_Conper", DbType="VarChar(50)")]
		public string Cor_Conper
		{
			get
			{
				return this._Cor_Conper;
			}
			set
			{
				if ((this._Cor_Conper != value))
				{
					this._Cor_Conper = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partner", DbType="VarChar(200)")]
		public string partner
		{
			get
			{
				return this._partner;
			}
			set
			{
				if ((this._partner != value))
				{
					this._partner = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AMC")]
	public partial class AMC
	{
		
		private string _AMC_Code;
		
		private string _AMC_Name;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _City;
		
		private string _Pin;
		
		private string _State;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private string _Phone3;
		
		private string _FAX;
		
		private string _E_Mail;
		
		private string _Web_Site;
		
		private string _Conper;
		
		public AMC()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMC_Code", DbType="VarChar(10)")]
		public string AMC_Code
		{
			get
			{
				return this._AMC_Code;
			}
			set
			{
				if ((this._AMC_Code != value))
				{
					this._AMC_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMC_Name", DbType="VarChar(80)")]
		public string AMC_Name
		{
			get
			{
				return this._AMC_Name;
			}
			set
			{
				if ((this._AMC_Name != value))
				{
					this._AMC_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(50)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(50)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(20)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="VarChar(6)")]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this._Pin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(20)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="VarChar(10)")]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this._Phone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="VarChar(10)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this._Phone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone3", DbType="VarChar(10)")]
		public string Phone3
		{
			get
			{
				return this._Phone3;
			}
			set
			{
				if ((this._Phone3 != value))
				{
					this._Phone3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="VarChar(10)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this._FAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Mail", DbType="VarChar(45)")]
		public string E_Mail
		{
			get
			{
				return this._E_Mail;
			}
			set
			{
				if ((this._E_Mail != value))
				{
					this._E_Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web_Site", DbType="VarChar(45)")]
		public string Web_Site
		{
			get
			{
				return this._Web_Site;
			}
			set
			{
				if ((this._Web_Site != value))
				{
					this._Web_Site = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conper", DbType="VarChar(45)")]
		public string Conper
		{
			get
			{
				return this._Conper;
			}
			set
			{
				if ((this._Conper != value))
				{
					this._Conper = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.top_fund")]
	public partial class top_fund
	{
		
		private string _sch_code;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<double> _per_7days;
		
		private System.Nullable<double> _per_15days;
		
		private System.Nullable<double> _per_30days;
		
		private System.Nullable<double> _per_91days;
		
		private System.Nullable<double> _per_182days;
		
		private System.Nullable<double> _per_1yr;
		
		private System.Nullable<double> _per_3yr;
		
		private System.Nullable<double> _since_incept;
		
		private System.Nullable<double> _div_yld;
		
		private string _nature;
		
		private System.Nullable<double> _per_5yr;
		
		public top_fund()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_code", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string sch_code
		{
			get
			{
				return this._sch_code;
			}
			set
			{
				if ((this._sch_code != value))
				{
					this._sch_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_7days", DbType="Float")]
		public System.Nullable<double> per_7days
		{
			get
			{
				return this._per_7days;
			}
			set
			{
				if ((this._per_7days != value))
				{
					this._per_7days = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_15days", DbType="Float")]
		public System.Nullable<double> per_15days
		{
			get
			{
				return this._per_15days;
			}
			set
			{
				if ((this._per_15days != value))
				{
					this._per_15days = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_30days", DbType="Float")]
		public System.Nullable<double> per_30days
		{
			get
			{
				return this._per_30days;
			}
			set
			{
				if ((this._per_30days != value))
				{
					this._per_30days = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_91days", DbType="Float")]
		public System.Nullable<double> per_91days
		{
			get
			{
				return this._per_91days;
			}
			set
			{
				if ((this._per_91days != value))
				{
					this._per_91days = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_182days", DbType="Float")]
		public System.Nullable<double> per_182days
		{
			get
			{
				return this._per_182days;
			}
			set
			{
				if ((this._per_182days != value))
				{
					this._per_182days = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_1yr", DbType="Float")]
		public System.Nullable<double> per_1yr
		{
			get
			{
				return this._per_1yr;
			}
			set
			{
				if ((this._per_1yr != value))
				{
					this._per_1yr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_3yr", DbType="Float")]
		public System.Nullable<double> per_3yr
		{
			get
			{
				return this._per_3yr;
			}
			set
			{
				if ((this._per_3yr != value))
				{
					this._per_3yr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_since_incept", DbType="Float")]
		public System.Nullable<double> since_incept
		{
			get
			{
				return this._since_incept;
			}
			set
			{
				if ((this._since_incept != value))
				{
					this._since_incept = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_div_yld", DbType="Float")]
		public System.Nullable<double> div_yld
		{
			get
			{
				return this._div_yld;
			}
			set
			{
				if ((this._div_yld != value))
				{
					this._div_yld = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nature", DbType="VarChar(25)")]
		public string nature
		{
			get
			{
				return this._nature;
			}
			set
			{
				if ((this._nature != value))
				{
					this._nature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_5yr", DbType="Float")]
		public System.Nullable<double> per_5yr
		{
			get
			{
				return this._per_5yr;
			}
			set
			{
				if ((this._per_5yr != value))
				{
					this._per_5yr = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REGIST")]
	public partial class REGIST
	{
		
		private string _Reg_Code;
		
		private string _Reg_Name;
		
		private string _Add1;
		
		private string _Add2;
		
		private string _City;
		
		private string _PIN;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private string _Phone3;
		
		private string _Fax;
		
		private string _E_Mail;
		
		private string _Web_Site;
		
		private string _Conper;
		
		public REGIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_Code", DbType="VarChar(10)")]
		public string Reg_Code
		{
			get
			{
				return this._Reg_Code;
			}
			set
			{
				if ((this._Reg_Code != value))
				{
					this._Reg_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_Name", DbType="VarChar(80)")]
		public string Reg_Name
		{
			get
			{
				return this._Reg_Name;
			}
			set
			{
				if ((this._Reg_Name != value))
				{
					this._Reg_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add1", DbType="VarChar(50)")]
		public string Add1
		{
			get
			{
				return this._Add1;
			}
			set
			{
				if ((this._Add1 != value))
				{
					this._Add1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add2", DbType="VarChar(50)")]
		public string Add2
		{
			get
			{
				return this._Add2;
			}
			set
			{
				if ((this._Add2 != value))
				{
					this._Add2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(20)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN", DbType="VarChar(6)")]
		public string PIN
		{
			get
			{
				return this._PIN;
			}
			set
			{
				if ((this._PIN != value))
				{
					this._PIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="VarChar(10)")]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this._Phone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="VarChar(10)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this._Phone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone3", DbType="VarChar(10)")]
		public string Phone3
		{
			get
			{
				return this._Phone3;
			}
			set
			{
				if ((this._Phone3 != value))
				{
					this._Phone3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(10)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Mail", DbType="VarChar(45)")]
		public string E_Mail
		{
			get
			{
				return this._E_Mail;
			}
			set
			{
				if ((this._E_Mail != value))
				{
					this._E_Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web_Site", DbType="VarChar(45)")]
		public string Web_Site
		{
			get
			{
				return this._Web_Site;
			}
			set
			{
				if ((this._Web_Site != value))
				{
					this._Web_Site = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conper", DbType="VarChar(45)")]
		public string Conper
		{
			get
			{
				return this._Conper;
			}
			set
			{
				if ((this._Conper != value))
				{
					this._Conper = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.latest_nav")]
	public partial class latest_nav
	{
		
		private string _Sch_Code;
		
		private System.DateTime _Date;
		
		private double _Nav_Rs;
		
		public latest_nav()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sch_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Sch_Code
		{
			get
			{
				return this._Sch_Code;
			}
			set
			{
				if ((this._Sch_Code != value))
				{
					this._Sch_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nav_Rs", DbType="Float NOT NULL")]
		public double Nav_Rs
		{
			get
			{
				return this._Nav_Rs;
			}
			set
			{
				if ((this._Nav_Rs != value))
				{
					this._Nav_Rs = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.div_rec")]
	public partial class div_rec
	{
		
		private string _Sch_code;
		
		private System.DateTime _Date;
		
		private System.Nullable<double> _Divid_pt;
		
		private System.DateTime _Record_date;
		
		private string _dividend;
		
		public div_rec()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sch_code", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Sch_code
		{
			get
			{
				return this._Sch_code;
			}
			set
			{
				if ((this._Sch_code != value))
				{
					this._Sch_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Divid_pt", DbType="Float")]
		public System.Nullable<double> Divid_pt
		{
			get
			{
				return this._Divid_pt;
			}
			set
			{
				if ((this._Divid_pt != value))
				{
					this._Divid_pt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Record_date", DbType="DateTime NOT NULL")]
		public System.DateTime Record_date
		{
			get
			{
				return this._Record_date;
			}
			set
			{
				if ((this._Record_date != value))
				{
					this._Record_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dividend", DbType="VarChar(10)")]
		public string dividend
		{
			get
			{
				return this._dividend;
			}
			set
			{
				if ((this._dividend != value))
				{
					this._dividend = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.net_ind_pot1")]
	public partial class net_ind_pot1
	{
		
		private string _Sch_Code;
		
		private string _Sect_Code;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<double> _Percent;
		
		public net_ind_pot1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sch_Code", DbType="VarChar(50)")]
		public string Sch_Code
		{
			get
			{
				return this._Sch_Code;
			}
			set
			{
				if ((this._Sch_Code != value))
				{
					this._Sch_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sect_Code", DbType="VarChar(50)")]
		public string Sect_Code
		{
			get
			{
				return this._Sect_Code;
			}
			set
			{
				if ((this._Sect_Code != value))
				{
					this._Sect_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Percent]", Storage="_Percent", DbType="Float")]
		public System.Nullable<double> Percent
		{
			get
			{
				return this._Percent;
			}
			set
			{
				if ((this._Percent != value))
				{
					this._Percent = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Invt_Pat")]
	public partial class Invt_Pat
	{
		
		private string _sch_code;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<double> _Equity;
		
		private System.Nullable<double> _Debt;
		
		private System.Nullable<double> _Cas_MonM;
		
		public Invt_Pat()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_code", DbType="VarChar(10)")]
		public string sch_code
		{
			get
			{
				return this._sch_code;
			}
			set
			{
				if ((this._sch_code != value))
				{
					this._sch_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equity", DbType="Float")]
		public System.Nullable<double> Equity
		{
			get
			{
				return this._Equity;
			}
			set
			{
				if ((this._Equity != value))
				{
					this._Equity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Debt", DbType="Float")]
		public System.Nullable<double> Debt
		{
			get
			{
				return this._Debt;
			}
			set
			{
				if ((this._Debt != value))
				{
					this._Debt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cas_MonM", DbType="Float")]
		public System.Nullable<double> Cas_MonM
		{
			get
			{
				return this._Cas_MonM;
			}
			set
			{
				if ((this._Cas_MonM != value))
				{
					this._Cas_MonM = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.top_hold")]
	public partial class top_hold
	{
		
		private string _Sch_Code;
		
		private System.Nullable<System.DateTime> _Date;
		
		private string _c_code;
		
		private string _c_name;
		
		private System.Nullable<double> _corpus_per;
		
		private System.Nullable<double> _Mkt_Value;
		
		private System.Nullable<double> _No_of_shares;
		
		private string _Instrument;
		
		private string _Nature;
		
		private System.Nullable<double> _Coupon_Rate;
		
		private string _Rating;
		
		private System.Nullable<System.DateTime> _Mt_Date;
		
		private string _Sect_code;
		
		private string _mt_date_txt;
		
		public top_hold()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sch_Code", DbType="VarChar(10)")]
		public string Sch_Code
		{
			get
			{
				return this._Sch_Code;
			}
			set
			{
				if ((this._Sch_Code != value))
				{
					this._Sch_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_code", DbType="VarChar(10)")]
		public string c_code
		{
			get
			{
				return this._c_code;
			}
			set
			{
				if ((this._c_code != value))
				{
					this._c_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_name", DbType="VarChar(80)")]
		public string c_name
		{
			get
			{
				return this._c_name;
			}
			set
			{
				if ((this._c_name != value))
				{
					this._c_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_corpus_per", DbType="Float")]
		public System.Nullable<double> corpus_per
		{
			get
			{
				return this._corpus_per;
			}
			set
			{
				if ((this._corpus_per != value))
				{
					this._corpus_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mkt_Value", DbType="Float")]
		public System.Nullable<double> Mkt_Value
		{
			get
			{
				return this._Mkt_Value;
			}
			set
			{
				if ((this._Mkt_Value != value))
				{
					this._Mkt_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_of_shares", DbType="Float")]
		public System.Nullable<double> No_of_shares
		{
			get
			{
				return this._No_of_shares;
			}
			set
			{
				if ((this._No_of_shares != value))
				{
					this._No_of_shares = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instrument", DbType="VarChar(50)")]
		public string Instrument
		{
			get
			{
				return this._Instrument;
			}
			set
			{
				if ((this._Instrument != value))
				{
					this._Instrument = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nature", DbType="VarChar(10)")]
		public string Nature
		{
			get
			{
				return this._Nature;
			}
			set
			{
				if ((this._Nature != value))
				{
					this._Nature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_Rate", DbType="Float")]
		public System.Nullable<double> Coupon_Rate
		{
			get
			{
				return this._Coupon_Rate;
			}
			set
			{
				if ((this._Coupon_Rate != value))
				{
					this._Coupon_Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="VarChar(10)")]
		public string Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this._Rating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mt_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Mt_Date
		{
			get
			{
				return this._Mt_Date;
			}
			set
			{
				if ((this._Mt_Date != value))
				{
					this._Mt_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sect_code", DbType="VarChar(10)")]
		public string Sect_code
		{
			get
			{
				return this._Sect_code;
			}
			set
			{
				if ((this._Sect_code != value))
				{
					this._Sect_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mt_date_txt", DbType="VarChar(15)")]
		public string mt_date_txt
		{
			get
			{
				return this._mt_date_txt;
			}
			set
			{
				if ((this._mt_date_txt != value))
				{
					this._mt_date_txt = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FundSize")]
	public partial class FundSize
	{
		
		private string _sch_Code;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<double> _fund_Size;
		
		public FundSize()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_Code", DbType="VarChar(10)")]
		public string sch_Code
		{
			get
			{
				return this._sch_Code;
			}
			set
			{
				if ((this._sch_Code != value))
				{
					this._sch_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fund_Size", DbType="Float")]
		public System.Nullable<double> fund_Size
		{
			get
			{
				return this._fund_Size;
			}
			set
			{
				if ((this._fund_Size != value))
				{
					this._fund_Size = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fund_Manager")]
	public partial class Fund_Manager
	{
		
		private string _Mut_Code;
		
		private string _Fund_Code;
		
		private string _Fund_Manager1;
		
		private string _Designation;
		
		private string _Schemes;
		
		private string _Age;
		
		private string _Edu_Qual;
		
		private string _Experience;
		
		private string _Views;
		
		private string _Photo;
		
		private string _Notes;
		
		private string _E_Mail;
		
		public Fund_Manager()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mut_Code", DbType="VarChar(10)")]
		public string Mut_Code
		{
			get
			{
				return this._Mut_Code;
			}
			set
			{
				if ((this._Mut_Code != value))
				{
					this._Mut_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fund_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Fund_Code
		{
			get
			{
				return this._Fund_Code;
			}
			set
			{
				if ((this._Fund_Code != value))
				{
					this._Fund_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Fund_Manager", Storage="_Fund_Manager1", DbType="VarChar(50)")]
		public string Fund_Manager1
		{
			get
			{
				return this._Fund_Manager1;
			}
			set
			{
				if ((this._Fund_Manager1 != value))
				{
					this._Fund_Manager1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="VarChar(50)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this._Designation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schemes", DbType="VarChar(200)")]
		public string Schemes
		{
			get
			{
				return this._Schemes;
			}
			set
			{
				if ((this._Schemes != value))
				{
					this._Schemes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="VarChar(3)")]
		public string Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edu_Qual", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Edu_Qual
		{
			get
			{
				return this._Edu_Qual;
			}
			set
			{
				if ((this._Edu_Qual != value))
				{
					this._Edu_Qual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Experience", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Experience
		{
			get
			{
				return this._Experience;
			}
			set
			{
				if ((this._Experience != value))
				{
					this._Experience = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Views", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Views
		{
			get
			{
				return this._Views;
			}
			set
			{
				if ((this._Views != value))
				{
					this._Views = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="VarChar(50)")]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this._Photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(50)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Mail", DbType="VarChar(50)")]
		public string E_Mail
		{
			get
			{
				return this._E_Mail;
			}
			set
			{
				if ((this._E_Mail != value))
				{
					this._E_Mail = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cur_fund_man")]
	public partial class cur_fund_man
	{
		
		private string _sch_code;
		
		private string _fund_code;
		
		private string _desgn;
		
		private System.Nullable<System.DateTime> _app_dt;
		
		private System.Nullable<System.DateTime> _ch_dt;
		
		public cur_fund_man()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_code", DbType="VarChar(10)")]
		public string sch_code
		{
			get
			{
				return this._sch_code;
			}
			set
			{
				if ((this._sch_code != value))
				{
					this._sch_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fund_code", DbType="VarChar(10)")]
		public string fund_code
		{
			get
			{
				return this._fund_code;
			}
			set
			{
				if ((this._fund_code != value))
				{
					this._fund_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desgn", DbType="VarChar(255)")]
		public string desgn
		{
			get
			{
				return this._desgn;
			}
			set
			{
				if ((this._desgn != value))
				{
					this._desgn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> app_dt
		{
			get
			{
				return this._app_dt;
			}
			set
			{
				if ((this._app_dt != value))
				{
					this._app_dt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ch_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> ch_dt
		{
			get
			{
				return this._ch_dt;
			}
			set
			{
				if ((this._ch_dt != value))
				{
					this._ch_dt = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nav_new")]
	public partial class nav_new
	{
		
		private string _Sch_Code;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<double> _Nav_Rs;
		
		public nav_new()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sch_Code", DbType="VarChar(10)")]
		public string Sch_Code
		{
			get
			{
				return this._Sch_Code;
			}
			set
			{
				if ((this._Sch_Code != value))
				{
					this._Sch_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nav_Rs", DbType="Float")]
		public System.Nullable<double> Nav_Rs
		{
			get
			{
				return this._Nav_Rs;
			}
			set
			{
				if ((this._Nav_Rs != value))
				{
					this._Nav_Rs = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mfi_news")]
	public partial class mfi_new
	{
		
		private string _news_headline;
		
		private string _news_subheading;
		
		private string _newspaper_name;
		
		private string _matter;
		
		private string _news_on_page;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private System.Nullable<System.DateTime> _DATE1;
		
		private string _Mut_Name;
		
		public mfi_new()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_headline", DbType="VarChar(100)")]
		public string news_headline
		{
			get
			{
				return this._news_headline;
			}
			set
			{
				if ((this._news_headline != value))
				{
					this._news_headline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_subheading", DbType="VarChar(150)")]
		public string news_subheading
		{
			get
			{
				return this._news_subheading;
			}
			set
			{
				if ((this._news_subheading != value))
				{
					this._news_subheading = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_newspaper_name", DbType="VarChar(50)")]
		public string newspaper_name
		{
			get
			{
				return this._newspaper_name;
			}
			set
			{
				if ((this._newspaper_name != value))
				{
					this._newspaper_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matter", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string matter
		{
			get
			{
				return this._matter;
			}
			set
			{
				if ((this._matter != value))
				{
					this._matter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_on_page", DbType="VarChar(1)")]
		public string news_on_page
		{
			get
			{
				return this._news_on_page;
			}
			set
			{
				if ((this._news_on_page != value))
				{
					this._news_on_page = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this._DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE1", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE1
		{
			get
			{
				return this._DATE1;
			}
			set
			{
				if ((this._DATE1 != value))
				{
					this._DATE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mut_Name", DbType="VarChar(80)")]
		public string Mut_Name
		{
			get
			{
				return this._Mut_Name;
			}
			set
			{
				if ((this._Mut_Name != value))
				{
					this._Mut_Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Com_detail")]
	public partial class Com_detail
	{
		
		private string _C_code;
		
		private string _C_Name;
		
		private string _RSTA_Code;
		
		private string _SD_Code;
		
		private string _CEO;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _City;
		
		private string _Pin;
		
		private string _State;
		
		private string _Phone1;
		
		private string _Phone2;
		
		private string _Phone3;
		
		private string _Fax;
		
		private string _Ex_Code;
		
		private string _Ind_Code;
		
		private string _Website;
		
		private string _Sect_Code;
		
		private string _bse_symb;
		
		private string _nse_symb;
		
		public Com_detail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_code", DbType="VarChar(10)")]
		public string C_code
		{
			get
			{
				return this._C_code;
			}
			set
			{
				if ((this._C_code != value))
				{
					this._C_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Name", DbType="VarChar(100)")]
		public string C_Name
		{
			get
			{
				return this._C_Name;
			}
			set
			{
				if ((this._C_Name != value))
				{
					this._C_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSTA_Code", DbType="VarChar(10)")]
		public string RSTA_Code
		{
			get
			{
				return this._RSTA_Code;
			}
			set
			{
				if ((this._RSTA_Code != value))
				{
					this._RSTA_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SD_Code", DbType="VarChar(10)")]
		public string SD_Code
		{
			get
			{
				return this._SD_Code;
			}
			set
			{
				if ((this._SD_Code != value))
				{
					this._SD_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEO", DbType="VarChar(50)")]
		public string CEO
		{
			get
			{
				return this._CEO;
			}
			set
			{
				if ((this._CEO != value))
				{
					this._CEO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(50)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(50)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(20)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="VarChar(6)")]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this._Pin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(20)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone1", DbType="VarChar(10)")]
		public string Phone1
		{
			get
			{
				return this._Phone1;
			}
			set
			{
				if ((this._Phone1 != value))
				{
					this._Phone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2", DbType="VarChar(10)")]
		public string Phone2
		{
			get
			{
				return this._Phone2;
			}
			set
			{
				if ((this._Phone2 != value))
				{
					this._Phone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone3", DbType="VarChar(10)")]
		public string Phone3
		{
			get
			{
				return this._Phone3;
			}
			set
			{
				if ((this._Phone3 != value))
				{
					this._Phone3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(10)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ex_Code", DbType="VarChar(10)")]
		public string Ex_Code
		{
			get
			{
				return this._Ex_Code;
			}
			set
			{
				if ((this._Ex_Code != value))
				{
					this._Ex_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ind_Code", DbType="VarChar(10)")]
		public string Ind_Code
		{
			get
			{
				return this._Ind_Code;
			}
			set
			{
				if ((this._Ind_Code != value))
				{
					this._Ind_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(50)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this._Website = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sect_Code", DbType="VarChar(10)")]
		public string Sect_Code
		{
			get
			{
				return this._Sect_Code;
			}
			set
			{
				if ((this._Sect_Code != value))
				{
					this._Sect_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bse_symb", DbType="VarChar(10)")]
		public string bse_symb
		{
			get
			{
				return this._bse_symb;
			}
			set
			{
				if ((this._bse_symb != value))
				{
					this._bse_symb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nse_symb", DbType="VarChar(10)")]
		public string nse_symb
		{
			get
			{
				return this._nse_symb;
			}
			set
			{
				if ((this._nse_symb != value))
				{
					this._nse_symb = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sector_ind")]
	public partial class Sector_ind
	{
		
		private string _Sect_code;
		
		private string _Sect_name;
		
		public Sector_ind()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sect_code", DbType="VarChar(10)")]
		public string Sect_code
		{
			get
			{
				return this._Sect_code;
			}
			set
			{
				if ((this._Sect_code != value))
				{
					this._Sect_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sect_name", DbType="VarChar(100)")]
		public string Sect_name
		{
			get
			{
				return this._Sect_name;
			}
			set
			{
				if ((this._Sect_name != value))
				{
					this._Sect_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.front_news")]
	public partial class front_new
	{
		
		private string _d_line;
		
		private string _headline;
		
		private string _yes_head;
		
		private string _category;
		
		private string _keyword;
		
		private string _author;
		
		private string _yes_author;
		
		private string _mut_code;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _matter;
		
		private string _article_no;
		
		private string _source;
		
		private string _sell;
		
		private string _photo;
		
		private System.Nullable<decimal> _priority;
		
		private string _blurr1;
		
		private string _blurr2;
		
		private string _html;
		
		private string _disp_ic;
		
		public front_new()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_line", DbType="VarChar(255)")]
		public string d_line
		{
			get
			{
				return this._d_line;
			}
			set
			{
				if ((this._d_line != value))
				{
					this._d_line = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_headline", DbType="VarChar(255)")]
		public string headline
		{
			get
			{
				return this._headline;
			}
			set
			{
				if ((this._headline != value))
				{
					this._headline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yes_head", DbType="VarChar(10)")]
		public string yes_head
		{
			get
			{
				return this._yes_head;
			}
			set
			{
				if ((this._yes_head != value))
				{
					this._yes_head = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="VarChar(100)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this._category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyword", DbType="VarChar(100)")]
		public string keyword
		{
			get
			{
				return this._keyword;
			}
			set
			{
				if ((this._keyword != value))
				{
					this._keyword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author", DbType="VarChar(100)")]
		public string author
		{
			get
			{
				return this._author;
			}
			set
			{
				if ((this._author != value))
				{
					this._author = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yes_author", DbType="VarChar(10)")]
		public string yes_author
		{
			get
			{
				return this._yes_author;
			}
			set
			{
				if ((this._yes_author != value))
				{
					this._yes_author = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mut_code", DbType="VarChar(10)")]
		public string mut_code
		{
			get
			{
				return this._mut_code;
			}
			set
			{
				if ((this._mut_code != value))
				{
					this._mut_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matter", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string matter
		{
			get
			{
				return this._matter;
			}
			set
			{
				if ((this._matter != value))
				{
					this._matter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_article_no", DbType="VarChar(10)")]
		public string article_no
		{
			get
			{
				return this._article_no;
			}
			set
			{
				if ((this._article_no != value))
				{
					this._article_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source", DbType="VarChar(20)")]
		public string source
		{
			get
			{
				return this._source;
			}
			set
			{
				if ((this._source != value))
				{
					this._source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sell", DbType="VarChar(10)")]
		public string sell
		{
			get
			{
				return this._sell;
			}
			set
			{
				if ((this._sell != value))
				{
					this._sell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="VarChar(20)")]
		public string photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this._photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priority", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				if ((this._priority != value))
				{
					this._priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blurr1", DbType="VarChar(100)")]
		public string blurr1
		{
			get
			{
				return this._blurr1;
			}
			set
			{
				if ((this._blurr1 != value))
				{
					this._blurr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blurr2", DbType="VarChar(100)")]
		public string blurr2
		{
			get
			{
				return this._blurr2;
			}
			set
			{
				if ((this._blurr2 != value))
				{
					this._blurr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_html", DbType="VarChar(50)")]
		public string html
		{
			get
			{
				return this._html;
			}
			set
			{
				if ((this._html != value))
				{
					this._html = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disp_ic", DbType="VarChar(1)")]
		public string disp_ic
		{
			get
			{
				return this._disp_ic;
			}
			set
			{
				if ((this._disp_ic != value))
				{
					this._disp_ic = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.net_com_pot")]
	public partial class net_com_pot
	{
		
		private string _Sch_Code;
		
		private System.Nullable<System.DateTime> _Date;
		
		private string _c_code;
		
		private string _c_name;
		
		private System.Nullable<double> _corpus_per;
		
		private System.Nullable<double> _Mkt_Value;
		
		private System.Nullable<double> _No_of_shares;
		
		private string _Instrument;
		
		private string _Nature;
		
		private System.Nullable<double> _Coupon_Rate;
		
		private string _Rating;
		
		private System.Nullable<System.DateTime> _Mt_Date;
		
		private string _Sect_code;
		
		private string _mt_date_txt;
		
		private System.Nullable<decimal> _INST_INFO_ID;
		
		public net_com_pot()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sch_Code", DbType="VarChar(10)")]
		public string Sch_Code
		{
			get
			{
				return this._Sch_Code;
			}
			set
			{
				if ((this._Sch_Code != value))
				{
					this._Sch_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_code", DbType="VarChar(10)")]
		public string c_code
		{
			get
			{
				return this._c_code;
			}
			set
			{
				if ((this._c_code != value))
				{
					this._c_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_name", DbType="VarChar(80)")]
		public string c_name
		{
			get
			{
				return this._c_name;
			}
			set
			{
				if ((this._c_name != value))
				{
					this._c_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_corpus_per", DbType="Float")]
		public System.Nullable<double> corpus_per
		{
			get
			{
				return this._corpus_per;
			}
			set
			{
				if ((this._corpus_per != value))
				{
					this._corpus_per = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mkt_Value", DbType="Float")]
		public System.Nullable<double> Mkt_Value
		{
			get
			{
				return this._Mkt_Value;
			}
			set
			{
				if ((this._Mkt_Value != value))
				{
					this._Mkt_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_of_shares", DbType="Float")]
		public System.Nullable<double> No_of_shares
		{
			get
			{
				return this._No_of_shares;
			}
			set
			{
				if ((this._No_of_shares != value))
				{
					this._No_of_shares = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instrument", DbType="VarChar(50)")]
		public string Instrument
		{
			get
			{
				return this._Instrument;
			}
			set
			{
				if ((this._Instrument != value))
				{
					this._Instrument = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nature", DbType="VarChar(10)")]
		public string Nature
		{
			get
			{
				return this._Nature;
			}
			set
			{
				if ((this._Nature != value))
				{
					this._Nature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_Rate", DbType="Float")]
		public System.Nullable<double> Coupon_Rate
		{
			get
			{
				return this._Coupon_Rate;
			}
			set
			{
				if ((this._Coupon_Rate != value))
				{
					this._Coupon_Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="VarChar(10)")]
		public string Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this._Rating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mt_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Mt_Date
		{
			get
			{
				return this._Mt_Date;
			}
			set
			{
				if ((this._Mt_Date != value))
				{
					this._Mt_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sect_code", DbType="VarChar(10)")]
		public string Sect_code
		{
			get
			{
				return this._Sect_code;
			}
			set
			{
				if ((this._Sect_code != value))
				{
					this._Sect_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mt_date_txt", DbType="VarChar(15)")]
		public string mt_date_txt
		{
			get
			{
				return this._mt_date_txt;
			}
			set
			{
				if ((this._mt_date_txt != value))
				{
					this._mt_date_txt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INST_INFO_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> INST_INFO_ID
		{
			get
			{
				return this._INST_INFO_ID;
			}
			set
			{
				if ((this._INST_INFO_ID != value))
				{
					this._INST_INFO_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sector")]
	public partial class Sector
	{
		
		private string _Sector1;
		
		private string _Sector_Code;
		
		public Sector()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Sector", Storage="_Sector1", DbType="VarChar(100)")]
		public string Sector1
		{
			get
			{
				return this._Sector1;
			}
			set
			{
				if ((this._Sector1 != value))
				{
					this._Sector1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sector_Code", DbType="VarChar(10)")]
		public string Sector_Code
		{
			get
			{
				return this._Sector_Code;
			}
			set
			{
				if ((this._Sector_Code != value))
				{
					this._Sector_Code = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sch_nature_details")]
	public partial class sch_nature_detail
	{
		
		private string _sch_code;
		
		private string _nature1;
		
		private string _subnature1;
		
		private string _nature2;
		
		private string _subnature2;
		
		private string _nature3;
		
		private string _subnature3;
		
		public sch_nature_detail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_code", DbType="VarChar(10)")]
		public string sch_code
		{
			get
			{
				return this._sch_code;
			}
			set
			{
				if ((this._sch_code != value))
				{
					this._sch_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nature1", DbType="VarChar(30)")]
		public string nature1
		{
			get
			{
				return this._nature1;
			}
			set
			{
				if ((this._nature1 != value))
				{
					this._nature1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subnature1", DbType="VarChar(30)")]
		public string subnature1
		{
			get
			{
				return this._subnature1;
			}
			set
			{
				if ((this._subnature1 != value))
				{
					this._subnature1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nature2", DbType="VarChar(30)")]
		public string nature2
		{
			get
			{
				return this._nature2;
			}
			set
			{
				if ((this._nature2 != value))
				{
					this._nature2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subnature2", DbType="VarChar(30)")]
		public string subnature2
		{
			get
			{
				return this._subnature2;
			}
			set
			{
				if ((this._subnature2 != value))
				{
					this._subnature2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nature3", DbType="VarChar(30)")]
		public string nature3
		{
			get
			{
				return this._nature3;
			}
			set
			{
				if ((this._nature3 != value))
				{
					this._nature3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subnature3", DbType="VarChar(30)")]
		public string subnature3
		{
			get
			{
				return this._subnature3;
			}
			set
			{
				if ((this._subnature3 != value))
				{
					this._subnature3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ind_info")]
	public partial class ind_info
	{
		
		private string _ind_code;
		
		private string _ind_name;
		
		private string _iss_body;
		
		private string _descr;
		
		private string _AssetClass;
		
		public ind_info()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ind_code", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ind_code
		{
			get
			{
				return this._ind_code;
			}
			set
			{
				if ((this._ind_code != value))
				{
					this._ind_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ind_name", DbType="VarChar(200)")]
		public string ind_name
		{
			get
			{
				return this._ind_name;
			}
			set
			{
				if ((this._ind_name != value))
				{
					this._ind_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iss_body", DbType="VarChar(200)")]
		public string iss_body
		{
			get
			{
				return this._iss_body;
			}
			set
			{
				if ((this._iss_body != value))
				{
					this._iss_body = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descr", DbType="VarChar(250)")]
		public string descr
		{
			get
			{
				return this._descr;
			}
			set
			{
				if ((this._descr != value))
				{
					this._descr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetClass", DbType="VarChar(50)")]
		public string AssetClass
		{
			get
			{
				return this._AssetClass;
			}
			set
			{
				if ((this._AssetClass != value))
				{
					this._AssetClass = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.amc_details")]
	public partial class amc_detail
	{
		
		private string _AMC_Code;
		
		private string _Detail1;
		
		private string _Detail2;
		
		private string _Detail3;
		
		private string _Key_Persons;
		
		private System.Nullable<double> _Total_Corpus__Crs_;
		
		public amc_detail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMC_Code", DbType="VarChar(10)")]
		public string AMC_Code
		{
			get
			{
				return this._AMC_Code;
			}
			set
			{
				if ((this._AMC_Code != value))
				{
					this._AMC_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail1", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Detail1
		{
			get
			{
				return this._Detail1;
			}
			set
			{
				if ((this._Detail1 != value))
				{
					this._Detail1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail2", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Detail2
		{
			get
			{
				return this._Detail2;
			}
			set
			{
				if ((this._Detail2 != value))
				{
					this._Detail2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail3", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Detail3
		{
			get
			{
				return this._Detail3;
			}
			set
			{
				if ((this._Detail3 != value))
				{
					this._Detail3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Key_Persons", DbType="VarChar(255)")]
		public string Key_Persons
		{
			get
			{
				return this._Key_Persons;
			}
			set
			{
				if ((this._Key_Persons != value))
				{
					this._Key_Persons = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Corpus__Crs_", DbType="Float")]
		public System.Nullable<double> Total_Corpus__Crs_
		{
			get
			{
				return this._Total_Corpus__Crs_;
			}
			set
			{
				if ((this._Total_Corpus__Crs_ != value))
				{
					this._Total_Corpus__Crs_ = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AverageCorpus")]
	public partial class AverageCorpus
	{
		
		private string _Mut_code;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<double> _Corpus_Crs_;
		
		private string _Investor_base;
		
		public AverageCorpus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mut_code", DbType="VarChar(10)")]
		public string Mut_code
		{
			get
			{
				return this._Mut_code;
			}
			set
			{
				if ((this._Mut_code != value))
				{
					this._Mut_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Corpus_Crs_", DbType="Float")]
		public System.Nullable<double> Corpus_Crs_
		{
			get
			{
				return this._Corpus_Crs_;
			}
			set
			{
				if ((this._Corpus_Crs_ != value))
				{
					this._Corpus_Crs_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Investor_base", DbType="VarChar(20)")]
		public string Investor_base
		{
			get
			{
				return this._Investor_base;
			}
			set
			{
				if ((this._Investor_base != value))
				{
					this._Investor_base = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AUM")]
	public partial class AUM
	{
		
		private System.Nullable<System.DateTime> _Date;
		
		private string _Sector;
		
		private System.Nullable<double> _New_Launched_Sales;
		
		private System.Nullable<double> _New_Schemes_Sales;
		
		private System.Nullable<double> _Exist_Schemes_Sales;
		
		private System.Nullable<double> _Redemption;
		
		private System.Nullable<double> _AUM1;
		
		private string _Notes;
		
		public AUM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sector", DbType="VarChar(100)")]
		public string Sector
		{
			get
			{
				return this._Sector;
			}
			set
			{
				if ((this._Sector != value))
				{
					this._Sector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_Launched_Sales", DbType="Float")]
		public System.Nullable<double> New_Launched_Sales
		{
			get
			{
				return this._New_Launched_Sales;
			}
			set
			{
				if ((this._New_Launched_Sales != value))
				{
					this._New_Launched_Sales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_Schemes_Sales", DbType="Float")]
		public System.Nullable<double> New_Schemes_Sales
		{
			get
			{
				return this._New_Schemes_Sales;
			}
			set
			{
				if ((this._New_Schemes_Sales != value))
				{
					this._New_Schemes_Sales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exist_Schemes_Sales", DbType="Float")]
		public System.Nullable<double> Exist_Schemes_Sales
		{
			get
			{
				return this._Exist_Schemes_Sales;
			}
			set
			{
				if ((this._Exist_Schemes_Sales != value))
				{
					this._Exist_Schemes_Sales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Redemption", DbType="Float")]
		public System.Nullable<double> Redemption
		{
			get
			{
				return this._Redemption;
			}
			set
			{
				if ((this._Redemption != value))
				{
					this._Redemption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AUM", Storage="_AUM1", DbType="Float")]
		public System.Nullable<double> AUM1
		{
			get
			{
				return this._AUM1;
			}
			set
			{
				if ((this._AUM1 != value))
				{
					this._AUM1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.amfi")]
	public partial class amfi
	{
		
		private string _type;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _nature;
		
		private System.Nullable<int> _new_sch;
		
		private System.Nullable<double> _new_sch_amt;
		
		private System.Nullable<int> _exists_sch;
		
		private System.Nullable<double> _exists_sch_amt;
		
		private System.Nullable<double> _redemption;
		
		private System.Nullable<double> _aum;
		
		private System.Nullable<int> _tot_sch;
		
		private System.Nullable<double> _tot_amt;
		
		public amfi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nature", DbType="VarChar(50)")]
		public string nature
		{
			get
			{
				return this._nature;
			}
			set
			{
				if ((this._nature != value))
				{
					this._nature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_new_sch", DbType="Int")]
		public System.Nullable<int> new_sch
		{
			get
			{
				return this._new_sch;
			}
			set
			{
				if ((this._new_sch != value))
				{
					this._new_sch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_new_sch_amt", DbType="Float")]
		public System.Nullable<double> new_sch_amt
		{
			get
			{
				return this._new_sch_amt;
			}
			set
			{
				if ((this._new_sch_amt != value))
				{
					this._new_sch_amt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exists_sch", DbType="Int")]
		public System.Nullable<int> exists_sch
		{
			get
			{
				return this._exists_sch;
			}
			set
			{
				if ((this._exists_sch != value))
				{
					this._exists_sch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exists_sch_amt", DbType="Float")]
		public System.Nullable<double> exists_sch_amt
		{
			get
			{
				return this._exists_sch_amt;
			}
			set
			{
				if ((this._exists_sch_amt != value))
				{
					this._exists_sch_amt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_redemption", DbType="Float")]
		public System.Nullable<double> redemption
		{
			get
			{
				return this._redemption;
			}
			set
			{
				if ((this._redemption != value))
				{
					this._redemption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aum", DbType="Float")]
		public System.Nullable<double> aum
		{
			get
			{
				return this._aum;
			}
			set
			{
				if ((this._aum != value))
				{
					this._aum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tot_sch", DbType="Int")]
		public System.Nullable<int> tot_sch
		{
			get
			{
				return this._tot_sch;
			}
			set
			{
				if ((this._tot_sch != value))
				{
					this._tot_sch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tot_amt", DbType="Float")]
		public System.Nullable<double> tot_amt
		{
			get
			{
				return this._tot_amt;
			}
			set
			{
				if ((this._tot_amt != value))
				{
					this._tot_amt = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.corpus")]
	public partial class corpus
	{
		
		private string _Mut_code;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<double> _Corpus_Crs_;
		
		private string _Investor_base;
		
		public corpus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mut_code", DbType="VarChar(10)")]
		public string Mut_code
		{
			get
			{
				return this._Mut_code;
			}
			set
			{
				if ((this._Mut_code != value))
				{
					this._Mut_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Corpus_Crs_", DbType="Float")]
		public System.Nullable<double> Corpus_Crs_
		{
			get
			{
				return this._Corpus_Crs_;
			}
			set
			{
				if ((this._Corpus_Crs_ != value))
				{
					this._Corpus_Crs_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Investor_base", DbType="VarChar(20)")]
		public string Investor_base
		{
			get
			{
				return this._Investor_base;
			}
			set
			{
				if ((this._Investor_base != value))
				{
					this._Investor_base = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Book_Close")]
	public partial class Book_Close
	{
		
		private string _Sch_Name;
		
		private string _Sch_code;
		
		private System.Nullable<System.DateTime> _BC_from;
		
		private System.Nullable<System.DateTime> _BC_Till;
		
		private string _Notice;
		
		public Book_Close()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sch_Name", DbType="VarChar(150)")]
		public string Sch_Name
		{
			get
			{
				return this._Sch_Name;
			}
			set
			{
				if ((this._Sch_Name != value))
				{
					this._Sch_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sch_code", DbType="VarChar(10)")]
		public string Sch_code
		{
			get
			{
				return this._Sch_code;
			}
			set
			{
				if ((this._Sch_code != value))
				{
					this._Sch_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BC_from", DbType="DateTime")]
		public System.Nullable<System.DateTime> BC_from
		{
			get
			{
				return this._BC_from;
			}
			set
			{
				if ((this._BC_from != value))
				{
					this._BC_from = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BC_Till", DbType="DateTime")]
		public System.Nullable<System.DateTime> BC_Till
		{
			get
			{
				return this._BC_Till;
			}
			set
			{
				if ((this._BC_Till != value))
				{
					this._BC_Till = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notice", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Notice
		{
			get
			{
				return this._Notice;
			}
			set
			{
				if ((this._Notice != value))
				{
					this._Notice = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mut_br")]
	public partial class mut_br
	{
		
		private string _Mut_Code;
		
		private string _BR_ADD1;
		
		private string _BR_ADD2;
		
		private string _BR_CITY;
		
		private string _BR_PIN;
		
		private string _Br_Phone1;
		
		private string _Br_Phone2;
		
		private string _Br_Phone3;
		
		private string _BR_CONPER;
		
		private string _BR_FAX;
		
		public mut_br()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mut_Code", DbType="VarChar(10)")]
		public string Mut_Code
		{
			get
			{
				return this._Mut_Code;
			}
			set
			{
				if ((this._Mut_Code != value))
				{
					this._Mut_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BR_ADD1", DbType="VarChar(500)")]
		public string BR_ADD1
		{
			get
			{
				return this._BR_ADD1;
			}
			set
			{
				if ((this._BR_ADD1 != value))
				{
					this._BR_ADD1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BR_ADD2", DbType="VarChar(500)")]
		public string BR_ADD2
		{
			get
			{
				return this._BR_ADD2;
			}
			set
			{
				if ((this._BR_ADD2 != value))
				{
					this._BR_ADD2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BR_CITY", DbType="VarChar(200)")]
		public string BR_CITY
		{
			get
			{
				return this._BR_CITY;
			}
			set
			{
				if ((this._BR_CITY != value))
				{
					this._BR_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BR_PIN", DbType="VarChar(60)")]
		public string BR_PIN
		{
			get
			{
				return this._BR_PIN;
			}
			set
			{
				if ((this._BR_PIN != value))
				{
					this._BR_PIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Br_Phone1", DbType="VarChar(100)")]
		public string Br_Phone1
		{
			get
			{
				return this._Br_Phone1;
			}
			set
			{
				if ((this._Br_Phone1 != value))
				{
					this._Br_Phone1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Br_Phone2", DbType="VarChar(100)")]
		public string Br_Phone2
		{
			get
			{
				return this._Br_Phone2;
			}
			set
			{
				if ((this._Br_Phone2 != value))
				{
					this._Br_Phone2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Br_Phone3", DbType="VarChar(100)")]
		public string Br_Phone3
		{
			get
			{
				return this._Br_Phone3;
			}
			set
			{
				if ((this._Br_Phone3 != value))
				{
					this._Br_Phone3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BR_CONPER", DbType="VarChar(500)")]
		public string BR_CONPER
		{
			get
			{
				return this._BR_CONPER;
			}
			set
			{
				if ((this._BR_CONPER != value))
				{
					this._BR_CONPER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BR_FAX", DbType="VarChar(100)")]
		public string BR_FAX
		{
			get
			{
				return this._BR_FAX;
			}
			set
			{
				if ((this._BR_FAX != value))
				{
					this._BR_FAX = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sale_purchase")]
	public partial class sale_purchase
	{
		
		private System.Nullable<System.DateTime> _date;
		
		private string _org;
		
		private string _nature;
		
		private string _sale;
		
		private string _purchase;
		
		public sale_purchase()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_org", DbType="VarChar(20)")]
		public string org
		{
			get
			{
				return this._org;
			}
			set
			{
				if ((this._org != value))
				{
					this._org = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nature", DbType="VarChar(20)")]
		public string nature
		{
			get
			{
				return this._nature;
			}
			set
			{
				if ((this._nature != value))
				{
					this._nature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sale", DbType="VarChar(10)")]
		public string sale
		{
			get
			{
				return this._sale;
			}
			set
			{
				if ((this._sale != value))
				{
					this._sale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_purchase", DbType="VarChar(10)")]
		public string purchase
		{
			get
			{
				return this._purchase;
			}
			set
			{
				if ((this._purchase != value))
				{
					this._purchase = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.exitentry_load")]
	public partial class exitentry_load
	{
		
		private string _sch_code;
		
		private System.DateTime _app_from;
		
		private System.Nullable<System.DateTime> _app_to;
		
		private string _ee_type;
		
		private System.Nullable<double> _ee_load;
		
		private int _cond_id;
		
		private string _cond_type;
		
		private System.Nullable<double> _g_cond;
		
		private string _dur_type1;
		
		private System.Nullable<double> _l_cond;
		
		private string _dur_type2;
		
		private System.Nullable<double> _cdsc;
		
		private string _remark;
		
		public exitentry_load()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_code", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string sch_code
		{
			get
			{
				return this._sch_code;
			}
			set
			{
				if ((this._sch_code != value))
				{
					this._sch_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_from", DbType="DateTime NOT NULL")]
		public System.DateTime app_from
		{
			get
			{
				return this._app_from;
			}
			set
			{
				if ((this._app_from != value))
				{
					this._app_from = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_to", DbType="DateTime")]
		public System.Nullable<System.DateTime> app_to
		{
			get
			{
				return this._app_to;
			}
			set
			{
				if ((this._app_to != value))
				{
					this._app_to = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ee_type", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ee_type
		{
			get
			{
				return this._ee_type;
			}
			set
			{
				if ((this._ee_type != value))
				{
					this._ee_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ee_load", DbType="Float")]
		public System.Nullable<double> ee_load
		{
			get
			{
				return this._ee_load;
			}
			set
			{
				if ((this._ee_load != value))
				{
					this._ee_load = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cond_id", DbType="Int NOT NULL")]
		public int cond_id
		{
			get
			{
				return this._cond_id;
			}
			set
			{
				if ((this._cond_id != value))
				{
					this._cond_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cond_type", DbType="VarChar(50)")]
		public string cond_type
		{
			get
			{
				return this._cond_type;
			}
			set
			{
				if ((this._cond_type != value))
				{
					this._cond_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_g_cond", DbType="Float")]
		public System.Nullable<double> g_cond
		{
			get
			{
				return this._g_cond;
			}
			set
			{
				if ((this._g_cond != value))
				{
					this._g_cond = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dur_type1", DbType="VarChar(10)")]
		public string dur_type1
		{
			get
			{
				return this._dur_type1;
			}
			set
			{
				if ((this._dur_type1 != value))
				{
					this._dur_type1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l_cond", DbType="Float")]
		public System.Nullable<double> l_cond
		{
			get
			{
				return this._l_cond;
			}
			set
			{
				if ((this._l_cond != value))
				{
					this._l_cond = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dur_type2", DbType="VarChar(10)")]
		public string dur_type2
		{
			get
			{
				return this._dur_type2;
			}
			set
			{
				if ((this._dur_type2 != value))
				{
					this._dur_type2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdsc", DbType="Float")]
		public System.Nullable<double> cdsc
		{
			get
			{
				return this._cdsc;
			}
			set
			{
				if ((this._cdsc != value))
				{
					this._cdsc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="VarChar(1000)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this._remark = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
